packages:
  - packages/*

catalogs:
  content:
    '@nuxt/content': ^3.8.2
    '@nuxtjs/seo': ^3.2.2
    '@shikijs/colorized-brackets': ^3.17.0
    '@shikijs/transformers': ^3.17.0
    abcjs: ^6.5.2
    nuxt-llms: ^0.1.3
    plain-shiki: ^0.3.2
    rehype-katex: ^7.0.1
    remark-abcjs: ^0.1.6
    remark-math: ^6.0.0
    remark-reading-time: ^2.0.2
    shiki: ^3.17.0
    unist-util-visit: ^5.0.0
  framework:
    '@zinkawaii/tsconfig': ^0.0.2
    ci-info: ^4.3.1
    nuxt: ^4.2.1
    sass-embedded: ^1.93.3
    tsdown: ^0.15.12
    tsx: ^4.20.6
    typescript: ^5.9.3
    unplugin-yaml: ^3.0.7
    vue: ^3.5.25
    vue-router: ^4.6.3
  quality:
    '@antfu/eslint-config': ^6.2.0
    '@nuxt/hints': ^1.0.0-alpha.2
    '@zinkawaii/stylelint-config': ^0.3.4
    cspell: ^9.3.2
    eslint: ^9.39.1
    stylelint: ^16.26.1
  ui:
    '@iconify-json/catppuccin': ^1.2.17
    '@iconify-json/ph': ^1.2.2
    '@iconify-json/ri': ^1.2.6
    '@iconify-json/simple-icons': ^1.2.60
    '@iconify-json/solar': ^1.2.5
    '@nuxt/icon': ^2.1.0
    '@nuxt/image': ^1.11.0
    '@nuxtjs/color-mode': ^3.5.2
    embla-carousel-autoplay: ^8.6.0
    embla-carousel-vue: ^8.6.0
    embla-carousel-wheel-gestures: ^8.1.0
    vue-tippy: ^6.7.1
    vue-virtual-scroller: 2.0.0-beta.8
  util:
    '@clack/prompts': ^0.11.0
    '@pinia/nuxt': ^0.11.3
    '@vueuse/core': ^14.1.0
    '@vueuse/nuxt': ^14.1.0
    '@vueuse/router': ^14.1.0
    date-fns: ^4.1.0
    date-fns-tz: ^3.2.0
    fast-xml-parser: ^5.3.2
    minisearch: ^7.2.0
    nanoid: ^5.1.6
    oxc-minify: ^0.96.0
    p-limit: ^7.2.0
    parse-domain: ^8.2.2
    radash: ^12.1.1
    rimraf: ^6.1.2
    site-config-stack: ^3.2.11
    strip-ansi: ^7.1.2

engineStrict: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - oxc-resolver
  - rolldown
  - sharp
  - unrs-resolver

patchedDependencies:
  '@nuxtjs/mdc': patches/@nuxtjs__mdc.patch
  '@vue/shared': patches/@vue__shared.patch
  plain-shiki: patches/plain-shiki.patch
  playwright-core: patches/playwright-core.patch

shamefullyHoist: true
