allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  oxc-resolver: true
  rolldown: true
  sharp: true
  unrs-resolver: true
  vue-demi: true

catalogs:
  content:
    '@bikariya/shiki': ^0.0.8
    '@nuxt/content': ^3.15.2
    '@nuxtjs/seo': ^5.3.12
    '@shikijs/colorized-brackets': ^4.4.3
    '@shikijs/transformers': ^4.4.3
    '@types/hast': ^3.0.5
    '@types/mdast': ^4.0.4
    abcjs: ^6.7.0
    minimark: 0.2.0
    nuxt-llms: ^0.2.0
    plain-shiki: ^0.3.2
    rehype-katex: ^7.0.1
    remark-math: ^6.0.0
    remark-reading-time: ^2.1.0
    shiki: ^4.4.3
    unist-util-visit: ^5.1.0
    vfile: ^6.0.3
    zod: ^4.4.3
  framework:
    '@zinkawaii/tsconfig': ^0.1.0
    ci-info: ^4.4.0
    nuxt: ^4.5.2
    pinia: ^4.0.2
    sass-embedded: ^1.100.0
    typescript: ^6.0.3
    unrun: ^0.3.1
    unplugin-yaml: ^4.2.1
    vue: ^3.5.41
    vue-router: ^5.2.0
  quality:
    '@antfu/eslint-config': ^9.3.0
    '@nuxt/a11y': 1.0.0-alpha.1
    '@nuxt/hints': ^1.1.4
    '@zinkawaii/stylelint-config': ^0.5.2
    cspell: ^10.0.1
    eslint: ^10.8.1
    stylelint: ^17.14.1
  ui:
    '@bikariya/image-viewer': ^0.0.8
    '@bikariya/modals': ^0.0.8
    '@iconify-json/catppuccin': ^1.2.17
    '@iconify-json/line-md': ^1.2.16
    '@iconify-json/ri': ^1.2.10
    '@iconify-json/simple-icons': ^1.2.93
    '@iconify-json/tabler': ^1.2.38
    '@nuxt/icon': ^2.5.0
    '@nuxt/image': ^2.1.0
    '@nuxtjs/color-mode': ^4.0.1
    embla-carousel-autoplay: ^8.6.0
    embla-carousel-vue: ^8.6.0
    embla-carousel-wheel-gestures: ^8.1.0
    vue-tippy: ^6.7.1
  util:
    '@clack/prompts': ^1.7.0
    '@pinia/nuxt': ^1.0.1
    '@vueuse/core': ^14.4.0
    '@vueuse/nuxt': ^14.4.0
    '@vueuse/router': ^14.4.0
    es-toolkit: ^1.50.0
    fast-xml-builder: ^1.3.0
    minisearch: ^7.2.0
    oxc-minify: ^0.144.0
    p-limit: ^7.3.1
    parse-domain: ^8.3.2
    rimraf: ^6.1.3
    site-config-stack: ^4.2.1
    strip-ansi: ^7.2.0
    temporal-polyfill: ^1.0.3

engineStrict: true

patchedDependencies:
  # 图片支持配置 1.5x 像素密度
  '@nuxt/image': patches/@nuxt__image.patch
  # 代码块不将 tab 转为空格
  # 行内代码 props.code 传入原文
  '@nuxtjs/mdc': patches/@nuxtjs__mdc.patch
  # IPX 的 Sharp 无法处理 ICO ，但改变运行时 NuxtImg provider 有类型问题 https://github.com/nuxt/image/issues/2174
  ipx: patches/ipx.patch
  # adoptedStyleSheet ::highlight 高亮选择器
  plain-shiki: patches/plain-shiki.patch

shamefullyHoist: true
