packages:
  - packages/*

catalogs:
  content:
    '@bikariya/shiki': ^0.0.8
    '@nuxt/content': ^3.12.0
    '@nuxtjs/seo': ^3.4.0
    '@shikijs/colorized-brackets': ^4.0.0
    '@shikijs/transformers': ^4.0.0
    '@types/hast': ^3.0.4
    '@types/mdast': ^4.0.4
    abcjs: ^6.6.2
    minimark: 0.2.0
    nuxt-llms: ^0.2.0
    plain-shiki: ^0.3.2
    rehype-katex: ^7.0.1
    remark-math: ^6.0.0
    remark-reading-time: ^2.0.2
    shiki: ^4.0.0
    unist-util-visit: ^5.1.0
    vfile: ^6.0.3
  framework:
    '@zinkawaii/tsconfig': ^0.1.0
    ci-info: ^4.4.0
    nuxt: ^4.3.1
    sass-embedded: ^1.97.3
    tsdown: ^0.20.3
    tsx: ^4.21.0
    typescript: ^5.9.3
    unplugin-yaml: ^4.0.0
    vue: ^3.5.29
    vue-router: ^5.0.3
  quality:
    '@antfu/eslint-config': ^7.6.1
    '@nuxt/a11y': 1.0.0-alpha.1
    '@nuxt/hints': 1.0.0-alpha.6
    '@zinkawaii/stylelint-config': ^0.4.0
    cspell: ^9.7.0
    eslint: ^10.0.2
    stylelint: ^17.4.0
  ui:
    '@bikariya/image-viewer': ^0.0.8
    '@bikariya/modals': ^0.0.8
    '@iconify-json/catppuccin': ^1.2.17
    '@iconify-json/ph': ^1.2.2
    '@iconify-json/ri': ^1.2.10
    '@iconify-json/simple-icons': ^1.2.71
    '@iconify-json/solar': ^1.2.5
    '@nuxt/icon': ^2.2.1
    '@nuxt/image': ^2.0.0
    '@nuxtjs/color-mode': ^4.0.0
    embla-carousel-autoplay: ^8.6.0
    embla-carousel-vue: ^8.6.0
    embla-carousel-wheel-gestures: ^8.1.0
    vue-tippy: ^6.7.1
    vue-virtual-scroller: 2.0.0-beta.8
  util:
    '@clack/prompts': ^1.0.1
    '@pinia/nuxt': ^0.11.3
    '@vueuse/core': ^14.2.1
    '@vueuse/nuxt': ^14.2.1
    '@vueuse/router': ^14.2.1
    fast-xml-parser: ^5.4.1
    minisearch: ^7.2.0
    oxc-minify: ^0.115.0
    p-limit: ^7.3.0
    parse-domain: ^8.2.2
    radash: ^12.1.1
    rimraf: ^6.1.3
    site-config-stack: ^3.2.21
    strip-ansi: ^7.2.0
    temporal-polyfill: ^0.3.0

engineStrict: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - oxc-resolver
  - rolldown
  - sharp
  - unrs-resolver

patchedDependencies:
  '@nuxt/image': patches/@nuxt__image.patch
  '@nuxtjs/mdc': patches/@nuxtjs__mdc.patch
  '@vue/shared': patches/@vue__shared.patch
  plain-shiki: patches/plain-shiki.patch
  playwright-core: patches/playwright-core.patch

shamefullyHoist: true
