import type { FeedGroup } from '~/types/feed'
import { getFavicon, getGhAvatar, getGhIcon, getQqAvatar, QqAvatarSize } from './utils/img'

export default [
	{
		name: '相谈甚多',
		desc: '',
		// @keep-sorted { "keys": ["date"] }
		entries: [
			{
				author: 'GuuGuai',
				sitenick: '杂记本',
				title: '古怪杂记本',
				desc: '一个什么都可能会写的博客',
				link: 'https://gug.thisis.host/',
				feed: 'https://gug.thisis.host/atom.xml',
				icon: getFavicon('gug.thisis.host'),
				avatar: 'https://cdn.libravatar.org/avatar/646331bff8f19a0e05679c3cc0fc54d6?s=160',
				archs: ['Hexo', 'Netlify'],
				date: '2024-01-29',
				comment: '高中同学，技术好友，爱好番剧/折腾。',
			},
			{
				author: 'isYangs',
				desc: '一个前端Bug构造师的博客',
				link: 'https://www.isyangs.cn/',
				feed: 'https://www.isyangs.cn/feed.xml',
				icon: 'https://www.isyangs.cn/favicon.svg',
				avatar: 'https://7.isyangs.cn/8/655c9835780a0-8.jpg',
				archs: ['Vue', '国内 CDN'],
				date: '2024-01-29',
				comment: '高中时认识的小学校友，目前从事前端开发。',
			},
			{
				author: 'KazariEX',
				sitenick: '微光档案',
				desc: '故事就是只为你一个人而存在的世界',
				link: 'https://archive.bikari.top/',
				feed: 'https://archive.bikari.top/feed',
				icon: 'https://archive.bikari.top/image/favicon.svg',
				avatar: getGhAvatar('KazariEX'),
				archs: ['Nuxt', 'Netlify'],
				date: '2024-01-30',
				comment: '“四邮四电”直系学长，Vue相关开发者，前端方面指引我不少。',
			},
			{
				author: 'Ariasaka',
				sitenick: '小窝',
				title: 'Ariasakaの小窝',
				desc: '人有悲欢离合 月有阴晴圆缺',
				link: 'https://blog.yaria.top/',
				feed: 'https://blog.yaria.top/feed',
				icon: 'https://blog.yaria.top/favicon.ico',
				avatar: getGhAvatar('LYXOfficial'),
				archs: ['Next.js', 'Vercel'],
				date: '2024-07-12',
				comment: '初中生，OIer，折腾博客。',
			},
			{
				author: '唤青',
				sitenick: 'Abloom',
				title: '唤青映记',
				desc: '我崇拜流浪、变化和幻想',
				link: 'https://eees.blog/',
				feed: 'https://eees.blog/atom.xml',
				icon: getGhIcon('abloom25'),
				avatar: getGhAvatar('abloom25'),
				archs: ['Hexo', 'Vercel'],
				date: '2024-12-09',
				comment: '初中生，技术学习中。',
			},
		],
	},
	{
		name: 'XUPTers',
		desc: '西安邮电大学的校友们。',
		// @keep-sorted { "keys": ["date"] }
		entries: [
			{
				author: '半岛的孤城',
				sitenick: '小屋',
				title: '半岛的小屋',
				desc: '不知道写啥，那就不写了。哎嘿',
				link: 'https://www.bandao.ltd/',
				feed: 'https://www.bandao.ltd/atom.xml',
				icon: getGhIcon('bandaoworld'),
				avatar: getGhAvatar('bandaoworld'),
				archs: ['Hexo', '服务器'],
				date: '2024-02-02',
				comment: '大学学长，爱好摄影/听歌，会一些Vue。',
			},
			{
				author: '学习爱我',
				sitenick: 'Studio',
				title: 'StudyingLover\'s Blog',
				desc: '要偷偷努力，下回惊艳所有人',
				link: 'https://www.studyinglover.com/',
				feed: 'https://www.studyinglover.com/rss.xml',
				icon: getGhIcon('StudyingLover'),
				avatar: getGhAvatar('StudyingLover'),
				archs: ['Astro', 'Vercel'],
				date: '2024-02-03',
				comment: '“学习哥”',
			},
			{
				author: 'Yuanfang',
				title: '元芳你怎么看',
				desc: '琼楼挂月钓流云，梦里瑶台暂借春',
				link: 'https://yuanfang.thisis.host/',
				icon: 'https://yuanfang.thisis.host/images/logo.svg',
				avatar: getGhAvatar('zhendewokusi'),
				archs: ['Hexo', 'Netlify'],
				date: '2024-02-06',
				comment: '大学同级，Linux内核学习中。',
			},
			{
				author: 'Ph0m',
				sitenick: 'Space',
				title: 'Ph0m\'s space',
				desc: '好好生活 慢慢相遇',
				link: 'https://blog.phom.space/',
				feed: 'https://blog.phom.space/atom.xml',
				icon: getGhIcon('Ph0m1'),
				avatar: 'https://pic.imgdb.cn/item/65e1df0c9f345e8d03bcdd6a.png',
				archs: ['Hexo', 'Netlify'],
				date: '2024-03-02',
				comment: '大学学弟。',
			},
			{
				author: 'Future',
				title: 'future\'s blog',
				desc: 'Hang on to your dreams!',
				link: 'https://future.thisis.host/',
				feed: 'https://future.thisis.host/atom.xml',
				icon: 'https://future.thisis.host/images/favicon-light-32.png',
				avatar: getGhAvatar('SIMple-lives'),
				archs: ['Hexo', 'Cloudflare'],
				date: '2024-03-10',
				comment: '大学学弟。',
			},
			{
				author: 'tiny-sky',
				title: 'tiny-sky的个人博客',
				desc: '人生苦短，及时行乐',
				link: 'https://tiny-sky.github.io/',
				icon: 'https://tiny-sky.github.io/img/pwa/favicon.ico',
				avatar: getGhAvatar('tiny-sky'),
				archs: ['Hexo', 'GitHub Pages'],
				date: '2024-04-03',
				comment: '大学同级，数据库学习中。',
			},
			{
				author: 'Shawn',
				sitenick: '笔记',
				title: 'Shawn的笔记',
				desc: 'Where there is a will, there is a way.',
				link: 'https://shawn.thisis.host/',
				feed: 'https://shawn.thisis.host/atom.xml',
				icon: getGhIcon('ShawnJeffersonWang'),
				avatar: getGhAvatar('ShawnJeffersonWang'),
				archs: ['Hexo', 'Cloudflare'],
				date: '2024-06-13',
				comment: '大学同级，Golang 学习中。',
			},
			// {
			// 	author: 'Kayle',
			// 	sitenick: '小站',
			// 	title: 'Kayle小站',
			// 	desc: '正在学习嵌入式',
			// 	link: 'https://www.kayle7.top/',
			// 	feed: 'https://www.kayle7.top/atom.xml',
			// 	icon: getQqAvatar('1239625475', QqAvatarSize.Size100),
			// 	avatar: getQqAvatar('1239625475'),
			// 	archs: ['Hexo', 'Cloudflare'],
			// 	date: '2024-06-27',
			// 	comment: '大学同级，嵌入式学习中。',
			// 	error: '域名过期',
			// },
			// {
			// 	author: '桃林饮酒',
			// 	title: '摆烂的桃的Blog',
			// 	desc: '回不去的何止时间',
			// 	link: 'https://www.taolin.site/',
			// 	feed: 'https://www.taolin.site/rss.xml',
			// 	icon: 'https://www.taolin.site/favicon.ico',
			// 	avatar: getGhAvatar('Taolinyinjiu'),
			// 	archs: ['Astro', 'Vercel'],
			// 	date: '2024-07-16',
			// 	comment: '大学同级，嵌入式学习中。',
			// 	error: '域名过期',
			// },
			{
				author: 'Magic462',
				title: 'MagicBlog',
				desc: '我知我喜乐，纵情跋涉。',
				link: 'https://magic.thisis.host/',
				feed: 'https://magic.thisis.host/atom.xml',
				icon: getQqAvatar('1623728267', QqAvatarSize.Size100),
				avatar: getQqAvatar('1623728267'),
				archs: ['Hexo', 'Cloudflare'],
				date: '2024-07-22',
				comment: '大学学妹，前端学习中。',
			},
			{
				author: 'fault123',
				title: 'fault`s blog',
				desc: '学习！学习！还是学习！当然也是要吃点好东西！',
				link: 'https://fault.thisis.host/',
				feed: 'https://fault.thisis.host/atom.xml',
				icon: getGhIcon('fault123'),
				avatar: getGhAvatar('fault123'),
				archs: ['Hexo', 'Netlify'],
				date: '2024-07-29',
				comment: '大学同级，网安学习中。',
			},
			{
				author: 'Monoceros406',
				title: 'The Blog of Monoceros406',
				desc: 'Reverse - 智邮普创工作室安全组/Nepnep联合战队',
				link: 'https://monoceros406.github.io/',
				feed: 'https://monoceros406.github.io/atom.xml',
				icon: getGhIcon('Monoceros406'),
				avatar: getGhAvatar('Monoceros406'),
				archs: ['Hexo', 'GitHub Pages'],
				date: '2024-07-29',
				comment: '大学学弟，网安Reverse学习中。',
			},
			{
				author: '云间世界',
				title: '云间的小小世界',
				desc: '顺着风的方向',
				link: 'https://yunjianworld.fun/',
				feed: 'https://yunjianworld.fun/atom.xml',
				icon: 'https://yunjianworld.fun/img/fluid.png',
				avatar: getQqAvatar('2098600899'),
				archs: ['Hexo', 'Cloudflare'],
				date: '2024-11-14',
				comment: '大学学妹，操作系统学习中。',
			},
			{
				author: '更多→',
				sitenick: '西邮Wiki',
				title: '西邮校友博客索引',
				desc: '西安邮电大学非官方校园生活指南',
				link: 'https://wiki.cooo.site/blog',
				icon: 'https://wiki.cooo.site/logo.svg',
				avatar: getGhAvatar('xupt-wiki'),
				archs: ['VitePress', '国内 CDN'],
				date: '2025-03-27',
				comment: '我和校友建立的校园Wiki，博客索引页面收录了校友博客。',
			},
		],
	},
	{
		name: '网上邻居',
		desc: '哔——啵——电波通讯中，欢迎常来串门。',
		// @keep-sorted { "keys": ["date"] }
		entries: [
			{
				author: '张洪Heo',
				desc: '分享设计与科技生活',
				link: 'https://blog.zhheo.com/',
				feed: 'https://blog.zhheo.com/atom.xml',
				icon: 'https://blog.zhheo.com/img/favicon4.0.webp',
				avatar: 'https://bu.dusays.com/2022/12/28/63ac2812183aa.png',
				archs: ['Hexo', '国内 CDN'],
				date: '2024-02-02',
				comment: '知名博主，其博客设计风格被众多人借鉴。',
			},
			{
				author: 'Revincx',
				sitenick: '小破站',
				title: 'Revincx的小破站',
				link: 'https://blog.revincx.icu/',
				feed: 'https://blog.revincx.icu/atom.xml',
				icon: 'https://blog.revincx.icu/images/favico.png',
				avatar: 'https://weavatar.com/avatar/20eed6a268787c9a751165bc1ec56e90',
				archs: ['Hexo', 'Vercel'],
				date: '2024-02-05',
				comment: '折腾。',
			},
			{
				author: 'L1nSn0w',
				title: 'L1nSn0w\'s Site',
				desc: '无限进步.🎈',
				link: 'https://log.vaaat.com/',
				feed: 'https://log.vaaat.com/index.xml',
				icon: 'https://log.vaaat.com/favicon.ico',
				avatar: getGhAvatar('lin-snow'),
				archs: ['Hugo', '国内 CDN'],
				date: '2024-02-14',
				comment: '广工学弟。',
			},
			{
				author: 'Yunyi',
				title: 'YUNYI BLOG',
				desc: '得闲饮茶~~~',
				link: 'https://www.yunyitang.me/',
				feed: 'https://www.yunyitang.me/atom.xml',
				icon: 'https://www.yunyitang.me/favicon/favicon.ico',
				avatar: 'https://www.yunyitang.me/img/Avatar.png',
				archs: ['Hexo', 'GitHub Pages'],
				date: '2024-02-18',
				comment: '很有博客的味道。',
			},
			{
				author: '晓空',
				sitenick: '空域',
				title: '晓空blog',
				desc: '探索更大的世界',
				link: 'https://blog.moeworld.tech/',
				feed: 'https://blog.moeworld.tech/feed/',
				icon: 'https://blog.moeworld.tech/wp-content/uploads/2024/08/cropped-favicon-32x32.png',
				avatar: 'https://blog.moeworld.tech/wp-content/themes/kratos-pjax-master/static/images/photo.jpg',
				archs: ['WordPress', 'Cloudflare'],
				date: '2024-02-25',
				comment: '技术折腾笔记。',
			},
			{
				author: 'Kegongteng',
				desc: 'Blogger / Technophile / Student',
				link: 'https://kegongteng.cn/',
				feed: 'https://kegongteng.cn/atom',
				icon: 'https://kegongteng.cn/favicon.ico',
				avatar: 'https://bu.dusays.com/2023/12/23/65867c3357bb6.jpg',
				archs: ['Next.js', 'Netlify'],
				date: '2024-02-25',
				comment: '有不错想法的中学生。',
			},
			{
				author: '斬風·千雪',
				sitenick: '風雪城',
				desc: '浩繁星空下的一场稚嫩的梦',
				link: 'https://blog.chyk.ink/',
				feed: 'https://blog.chyk.ink/atom.xml',
				icon: getGhIcon('chiyuki0325'),
				avatar: getQqAvatar('3526514925'),
				archs: ['Hexo', 'Vercel'],
				date: '2024-03-03',
				comment: 'Archlinux，折腾，大学生。',
			},
			{
				author: '清羽飞扬',
				title: 'LiuShen\'s Blog',
				desc: '柳影曳曳，清酒孤灯，扬笔撒墨，心境如霜',
				link: 'https://blog.liushen.fun/',
				feed: 'https://blog.liushen.fun/atom.xml',
				icon: 'https://blog.liushen.fun/info/avatar.ico',
				avatar: 'https://weavatar.com/avatar/92c15d4a1d99a8ee04b986a14a5f7e009e574b3383fc575005947988ccf205e2',
				archs: ['Hexo', '国内 CDN'],
				date: '2024-06-02',
				comment: '武理工学长，西安老乡。',
			},
			{
				author: 'awaae',
				sitenick: '呓语梦轩',
				desc: '用心享受生活',
				link: 'https://blog.awaae001.top/',
				feed: 'https://blog.awaae001.top/atom.xml',
				icon: getFavicon('blog.awaae001.top'),
				avatar: 'https://image.m-c.top/?/images/2024/01/13/Pqeh0v6VaK/ico.jpg',
				archs: ['Hexo', '国内 CDN'],
				date: '2024-06-05',
				comment: '有思考的高中生。',
			},
			{
				author: '氿月',
				sitenick: '寂白沙洲冷',
				desc: 'Et in Arcadia, ego.',
				link: 'https://chuishen.xyz/',
				feed: 'https://chuishen.xyz/atom.xml',
				icon: 'https://chuishen.xyz/img/logo.png',
				avatar: 'https://cravatar.cn/avatar/57ff1222a81493a0e72782530e77b269?s=160',
				archs: ['Hexo', 'Vercel'],
				date: '2024-06-16',
				comment: '虚构文学。',
			},
			{
				author: '晚夜',
				desc: '做好量变的准备，促进事物的质变。',
				link: 'https://www.iczrx.cn/',
				feed: 'https://www.iczrx.cn/feed/',
				icon: 'https://www.iczrx.cn/favicon.ico',
				avatar: getQqAvatar('1463656527'),
				archs: ['Typecho', '国内 CDN'],
				date: '2024-07-11',
				comment: '分享折腾与生活的高中生。',
			},
			{
				author: '春日心动日记',
				title: '春日心动日记',
				desc: 'Live and learn. 🌱',
				link: 'https://blog.mletter.cn/',
				icon: 'https://blog.mletter.cn/favicon/favicon-32x32.png',
				avatar: 'https://img13.360buyimg.com/ddimg/jfs/t1/239095/17/9691/19853/664d82dfF34a0990c/c4198876146be2d4.jpg',
				archs: ['Astro', 'Vercel'],
				date: '2024-07-11',
				comment: '在读运维开发工程师，记录技术和生活日常。',
			},
			{
				author: '天翔TNXG',
				sitenick: '空间站',
				title: '天翔TNXGの空间站',
				desc: '明日尚未到来，希望凝于心上',
				link: 'https://www.tnxgmoe.com/',
				feed: 'https://www.tnxgmoe.com/feed',
				icon: 'https://www.tnxgmoe.com/favicon.png',
				avatar: 'https://api-space.tnxg.top/avatar?s=qq',
				archs: ['Mix Space', 'Vercel'],
				date: '2024-07-11',
				comment: '西北地区高中生，开源爱好者。',
			},
			{
				author: 'Winner365',
				sitenick: '云栈',
				title: '365云栈',
				desc: '初阅不明言外意，重温方觉字中情',
				link: 'https://blog.365sites.top/',
				feed: 'https://blog.365sites.top/rss.xml',
				icon: getGhIcon('Winner365-China'),
				avatar: 'https://blog.365sites.top/upload/avatar.png',
				archs: ['Halo', 'Cloudflare'],
				date: '2024-07-14',
				comment: '学生，折腾博客。',
			},
			{
				author: 'FloatSheep',
				title: 'FloatSheep\'s Blog',
				desc: 'On the other side of obstacles',
				link: 'https://blog.hesiy.cn/',
				feed: 'https://blog.hesiy.cn/posts/index.xml',
				icon: 'https://blog.hesiy.cn/favicon-32x32.png',
				avatar: getGhAvatar('FloatSheep'),
				archs: ['Hugo', 'Cloudflare'],
				date: '2024-07-24',
				comment: '喜欢折腾。',
			},
			{
				author: 'Henry Moreau',
				title: '一站 - Henry的博客',
				desc: 'Student / Designer / Dreamchaser',
				link: 'https://blog.henrywhu.cn/',
				feed: 'https://blog.henrywhu.cn/atom.xml',
				icon: 'https://blog.henrywhu.cn/favicon.ico',
				avatar: 'https://bu.dusays.com/2024/06/28/667e684e0adbe.png',
				archs: ['Gridea', '服务器'],
				date: '2024-07-24',
				comment: '高中生，很有博客的味道。',
			},
			{
				author: 'Xlenco',
				sitenick: '希乐博客',
				desc: '互联网中的静谧之地',
				link: 'https://blog.xlenco.top/',
				feed: 'https://blog.xlenco.top/atom.xml',
				icon: 'https://weavatar.com/avatar/67254b346498965226e5c91ebff66a69570b97f224d2d061e504b4eade1f00fa',
				avatar: getQqAvatar('1043865083'),
				archs: ['Nuxt', '国内 CDN'],
				date: '2024-07-28',
				comment: '学生，经验分享。',
			},
			{
				author: '十玖八柒',
				sitenick: 'Z次元',
				desc: '探索代码的世界，追寻生活的诗篇',
				link: 'https://blog.ahzoo.cn/',
				feed: 'https://blog.ahzoo.cn/rss.xml',
				icon: 'https://blog.ahzoo.cn/favicon.ico',
				avatar: 'https://ahzoo.cn/img/avatar.webp',
				archs: ['Nuxt', '服务器'],
				date: '2024-08-02',
				comment: 'Nuxt博客，技术笔记。',
			},
			{
				author: 'iMaeGoo',
				sitenick: '空间站',
				title: '虹墨空间站',
				desc: '虹墨空间站',
				link: 'https://www.imaegoo.com/',
				feed: 'https://www.imaegoo.com/atom.xml',
				icon: 'https://www.imaegoo.com/favicon.ico',
				avatar: 'https://www.imaegoo.com/images/avatar.jpg',
				archs: ['Hexo', '国内 CDN'],
				date: '2024-08-19',
				comment: '前端折腾。',
			},
			{
				author: 'DuckXu',
				sitenick: 'Notebook',
				title: 'DuckXu\'s Notebook',
				desc: 'DuckXu\'s Internet home',
				link: 'https://i.duckxu.com/',
				feed: 'https://i.duckxu.com/rss.xml',
				icon: 'https://kycloud3.koyoo.cn/2024080228778202408022342057562.png',
				avatar: 'https://media.duckxu.com/blogfiles/public/iduckxucom.jpg',
				archs: ['Typecho', '服务器'],
				date: '2024-08-20',
				comment: '学生，记录生活思考。',
			},
			{
				author: '梦爱吃鱼',
				desc: '但愿日子清静抬头遇见的满是柔情',
				link: 'https://blog.bsgun.cn/',
				feed: 'https://blog.bsgun.cn/atom.xml',
				icon: 'https://bsgun.cn/favicon.ico',
				avatar: 'https://oss-cdn.bsgun.cn/logo/avatar.256.png',
				archs: ['Hexo', '国内 CDN'],
				date: '2024-08-20',
				comment: '博客折腾。',
			},
			{
				author: 'DengQN',
				title: 'DengQN\'s Blog',
				desc: '普通程序员',
				link: 'https://dengqn.com/',
				feed: 'https://dengqn.com/feed',
				icon: 'https://dengqn.com/favicon.ico',
				avatar: 'https://dengqn.com/image/headimg.png',
				archs: ['Vue', '服务器'],
				date: '2024-09-18',
				comment: '技术吐槽和运维记录。',
			},
			{
				author: 'LineXic',
				desc: '念念不忘，必有回响',
				link: 'https://www.linexic.top/',
				feed: 'https://www.linexic.top/rss.xml',
				icon: 'https://www.linexic.top/logo.png',
				avatar: 'https://www.linexic.top/avatar.webp',
				archs: ['Astro', 'Netlify'],
				date: '2024-10-02',
				comment: '前端学习，高中生活。',
			},
			{
				author: 'tinsir888',
				desc: 'Ηλύσια Πεδία',
				title: 'min hjemmeside',
				link: 'https://tinsir888.github.io/',
				feed: 'https://tinsir888.github.io/atom.xml',
				icon: getGhIcon('tinsir888'),
				avatar: getGhAvatar('tinsir888'),
				archs: ['Hexo', 'GitHub Pages'],
				date: '2024-10-18',
				comment: '计算机科学，留学生活。',
			},
			{
				author: '鹊楠',
				sitenick: '小窝',
				title: '鹊楠の小窝',
				desc: '世界那么大，我想去看看',
				link: 'https://blog.quenan.cn/',
				feed: 'https://blog.quenan.cn/atom.xml',
				icon: 'https://tuchuang.voooe.cn/images/2024/01/29/logo_icon.png',
				avatar: getGhAvatar('QNquenan'),
				archs: ['Hexo', '国内 CDN'],
				date: '2024-10-22',
				comment: '学生，技术分享。',
			},
			{
				author: 'XAOXUU',
				desc: '风暴前夕',
				link: 'https://xaoxuu.com/',
				feed: 'https://xaoxuu.com/atom.xml',
				icon: getGhIcon('xaoxuu'),
				avatar: getGhAvatar('xaoxuu'),
				archs: ['Hexo', '服务器'],
				date: '2024-10-26',
			},
			{
				author: 'Redish101',
				title: 'Redish101 Blog',
				desc: '学生，人，活的',
				link: 'https://blog.redish101.top/',
				feed: 'https://blog.redish101.top/feed',
				icon: getGhIcon('Redish101'),
				avatar: getGhAvatar('Redish101'),
				archs: ['Next.js', 'Vercel'],
				date: '2024-10-27',
				comment: '江湖人称数据库，初中生，博客开发中。',
			},
			{
				author: 'Pinpe',
				sitenick: '云端',
				title: 'Pinpe的云端',
				desc: '一个属于自己的云朵。',
				link: 'https://pinpe.top/',
				feed: 'https://pinpe.top/rss.xml',
				icon: 'https://pinpe.top/favicon/logo.png', // expected
				avatar: 'https://pinpe.top/head.jpg',
				archs: ['Astro', 'Vercel'],
				date: '2024-10-31',
				comment: '学生，奇妙幻想和思考。',
			},
			{
				author: '水氵冫',
				sitenick: '微霞',
				desc: '水风清，晚霞明',
				link: 'https://yuuu.org/',
				feed: 'https://yuuu.org/atom.xml',
				icon: 'https://cdn.yuuu.org/img/favicon-32x32.png',
				avatar: 'https://cdn.yuuu.org/img/avatar.webp',
				archs: ['Hexo', 'Vercel'],
				date: '2024-11-03',
				comment: '学生，技术分享，生活。',
			},
			{
				author: 'Tianli',
				desc: '自知之明是最可贵的知识！',
				link: 'https://blog.tianli0.top/',
				feed: 'https://blog.tianli0.top/rss.xml',
				icon: getGhIcon('tianli0'),
				avatar: getGhAvatar('tianli0'),
				archs: ['VitePress', '国内 CDN'],
				date: '2024-12-04',
				comment: '技术学习笔记，TianliGPT开发者。',
			},
			{
				author: '花生莲子粥',
				desc: '与世无争，不染于泥',
				link: 'https://blog.hslzz.cn/',
				icon: 'https://blog.hslzz.cn/favicon.ico',
				avatar: 'https://blog.hslzz.cn/img/avatar.png',
				archs: ['Hexo', '国内 CDN'],
				date: '2025-01-03',
				comment: 'Linux系统配置、服务部署、Hexo优化等技术教程，',
			},
			{
				author: '伍十七',
				sitenick: 'everfu',
				desc: '你好👋，我是伍十七，一个三流编程狮。',
				link: 'https://www.efu.me/',
				icon: 'https://www.efu.me/favicon.ico',
				avatar: getGhAvatar('everfu'),
				archs: ['Nuxt', '国内 CDN'],
				date: '2025-01-12',
				comment: 'Hexo Solitude 主题作者，经常换自己网站。',
			},
			{
				author: '鸢栀',
				sitenick: '仓库',
				title: '鸢栀的仓库',
				desc: '每天写下自己的喜欢',
				link: 'https://yuazhi.cn/',
				icon: 'https://yuazhi.cn/yuazhi.ico',
				avatar: 'https://weavatar.com/avatar/1dc444f85a6673099a47170588bbc6d7?s=96',
				archs: ['HTML', '服务器'],
				date: '2025-02-12',
				comment: '日常、前端、福瑞。',
			},
			{
				author: '阿呆',
				title: '阿呆的博客',
				desc: '分享，学习有趣的知识',
				link: 'https://www.adai.fun/',
				feed: 'https://www.adai.fun/atom.xml',
				icon: 'https://www.adai.fun/favicon.ico', // expected
				avatar: 'https://www.adai.fun/img/adai.png',
				archs: ['Hexo', 'Vercel'],
				date: '2025-03-11',
				comment: '技术分享与生活。',
			},
			{
				author: '葱苓',
				sitenick: '语畔',
				title: '葱苓语畔',
				desc: 'Don\'t worry, be happy.',
				link: 'https://blog.ciraos.top/',
				feed: 'https://blog.ciraos.top/feed.xml',
				icon: 'https://blog.ciraos.top/favicon.ico',
				avatar: getGhAvatar('ciraos'),
				archs: ['Hexo', '国内 CDN'],
				date: '2025-03-28',
				comment: '前端学习。',
			},
			{
				author: '南蛮子懋和',
				desc: '李懋和，俗名李栋梁。书法、国画爱好者，互联网安全与前端建设者。',
				link: 'https://www.dao.js.cn/',
				feed: 'https://www.dao.js.cn/feed.php',
				icon: 'https://www.dao.js.cn/zb_users/upload/2024/09/202409191726720024363275.png',
				avatar: getQqAvatar('466660026'),
				archs: ['ZBlog', '国内 CDN'],
				date: '2025-04-14',
				comment: '懋和道人，聚焦网站建设与技术，弘扬传统文化。',
			},
			{
				author: 'iFluxArt',
				desc: '斐启智境 · 流韵新生',
				link: 'https://www.iflux.art/',
				icon: 'https://www.iflux.art/favicon.ico',
				avatar: 'https://www.iflux.art/favicon.ico',
				archs: ['Next.js', 'Vercel'],
				date: '2025-04-16',
				comment: '文档型知识库，含AIGC、开发、设计、运营、传媒、工具等内容。',
			},
			{
				author: 'ZL Asica',
				title: 'ZLA 小站',
				desc: '月亮不抱你，星星会落在你怀里✨🌙',
				link: 'https://zla.pub/',
				feed: 'https://zla.pub/feed.xml',
				icon: getGhIcon('ZL-Asica'),
				avatar: getGhAvatar('ZL-Asica'),
				archs: ['Next.js', 'Vercel'],
				date: '2025-04-29',
				comment: '机器学习、前端开发、旅游经历。',
			},
			{
				author: '竹林里有冰',
				title: '竹林里有冰的博客',
				desc: '仍然在划水的菜鸡',
				link: 'https://zhul.in/',
				feed: 'https://zhul.in/rss.xml',
				icon: 'https://zhul.in/favicon.ico',
				avatar: 'https://static.031130.xyz/avatar.webp',
				archs: ['Hexo', '服务器'],
				date: '2025-05-03',
				comment: '前端开发、网络配置、服务器运维及开源工具实战经验。',
			},
			{
				author: '东方月初',
				sitenick: 'BiuXin',
				title: 'BiuXin-s Blog',
				desc: '人生的每一天，都在学习当中',
				link: 'https://zhilu.biuxin.com/',
				feed: 'https://zhilu.biuxin.com/atom.xml',
				icon: 'https://x.xinb.de/i/2024/09/19/040857.webp',
				avatar: getGhAvatar('damizai'),
				archs: ['Nuxt', '国内 CDN'],
				date: '2025-05-09',
				comment: '软件工具资源，博客部署美化。',
			},
			{
				author: 'shenley',
				sitenick: '存档点',
				title: 'shenley的存档点',
				desc: '随手存个档～',
				link: 'https://blog.ykrazy.top/',
				feed: 'https://blog.ykrazy.top/atom.xml',
				icon: 'https://blog.ykrazy.top/avatar.jpg',
				avatar: 'https://blog.ykrazy.top/avatar.jpg',
				archs: ['Nuxt', 'Vercel'],
				date: '2025-05-20',
				comment: '前端开发、生活分享。',
			},
			{
				author: '大马数字生活',
				title: '大马数字生活-digital life my',
				desc: '本部落格是一个专门分享生活在马来西亚，有关数字生活的内容包含：生活方式 个人经历 使用体验 评测分析 数码产品 分享内容 海外消费 海外通讯等内容。',
				link: 'https://digitallife.my/',
				feed: 'https://digitallife.my/feed/',
				icon: 'https://digitallife.my/favicon.ico',
				avatar: 'https://digitallife.my/wp-content/uploads/2025/06/cropped-1751133864-bloglogo.jpg',
				archs: ['WordPress', 'Cloudflare'],
				date: '2025-06-29',
				comment: '大马数字生活及相关海外账户等事宜。',
			},
			{
				author: '路狐羽',
				sitenick: '羽音',
				title: '羽音 × Seraphonogram',
				desc: '一只毛茸茸的博客',
				link: 'https://blog.navifox.net/',
				icon: 'https://blog.navifox.net/favicon.ico',
				avatar: 'https://blog.navifox.net/favicon.ico',
				archs: ['VitePress', '服务器'],
				date: '2025-07-14',
				comment: 'Python、Django 等编程知识、开发工具使用及算法题解等内容。',
			},
			{
				author: '月空人',
				desc: '偶尔写些博客，发发牢骚',
				link: 'https://whbbit.cn/',
				feed: 'https://whbbit.cn/atom.xml',
				icon: 'https://7.isyangs.cn/78/6795a3b5015e1-78.webp',
				avatar: 'https://7.isyangs.cn/78/6795a3b5015e1-78.webp',
				archs: ['Nuxt', '服务器'],
				date: '2025-07-28',
				comment: '分享 Vue、Nuxt 等前端技术的使用技巧、版本特性、工具集成及相关翻译文章。',
			},
			{
				author: 'Teror Fox',
				sitenick: '客栈',
				title: 'Teror的客栈',
				desc: '欢迎光临～',
				link: 'https://blog.trfox.top/',
				feed: 'https://blog.trfox.top/atom.xml',
				icon: 'https://blog.trfox.top/favicon.ico',
				avatar: 'https://img.trfox.top/assets/avatar.jpg',
				archs: ['Mix Space', 'Vercel'],
				date: '2025-08-03',
				comment: '技术相关的木马免杀测试、服务器处理与迁移、工具美化，以及个人博客系统更新、回归记录等。',
			},
			{
				author: '落憾',
				sitenick: 'EnLtLH',
				title: '落憾',
				desc: '建此博客，以示吾思。话天篆地，自由吾心。',
				link: 'https://blog.enltlh.me/',
				feed: 'https://blog.enltlh.me/atom.xml',
				icon: 'https://cdn2.enltlh.me/pichub/1/2025/19e0fab452a27b75.png',
				avatar: 'https://cdn2.enltlh.me/pichub/1/2025/2231d2da22a739df.jpg',
				archs: ['Nuxt', 'Vercel'],
				date: '2025-08-17',
				comment: '中学生，以诗词、杂记等形式记录感悟与创作。',
			},
			{
				author: 'AirTouch',
				desc: '分享技术、生活、思考。',
				link: 'https://www.xsl.im/',
				feed: 'https://www.xsl.im/atom.xml',
				icon: 'https://www.xsl.im/favicon.webp',
				avatar: 'https://www.xsl.im/avatar.webp',
				archs: ['Hexo', 'Vercel'],
				date: '2025-08-18',
				comment: '网站反代配置、服务器评测、域名更换、存储加速、工具推荐、编程题解等折腾与技术分享。',
			},
			{
				author: '青序栈',
				desc: '青序成栈·向简而生',
				link: 'https://qxzhan.cn/',
				feed: 'https://qxzhan.cn/feed/',
				icon: 'https://qxzhan.cn/favicon.png',
				avatar: 'https://qxzhan.cn/favicon.png',
				archs: ['Typecho', '国内 CDN'],
				date: '2025-08-20',
				comment: '网站攻击处理曝光，博客配置魔改等技术教程与资源分享。',
			},
			{
				author: 'Snowykami',
				sitenick: '空间站',
				title: '粒子空间站',
				desc: '轻思若水，雪化生香',
				link: 'https://blog.sfkm.me/',
				feed: 'https://blog.sfkm.me/feed.xml',
				icon: getQqAvatar('2751454815', QqAvatarSize.Size100),
				avatar: getQqAvatar('2751454815'),
				archs: ['Hexo', '国内 CDN'],
				date: '2025-08-25',
				comment: '云原生、HomeLab 搭建、网络安全、容器化、静态网站托管等领域的技术实践。',
			},
			{
				author: 'Restent Ou',
				title: 'Restent\'s Notebook',
				desc: 'Secret with Silent.',
				link: 'https://blog.gxres.net/',
				feed: 'https://blog.gxres.net/atom.xml',
				icon: 'https://library.gxres.net/images/icons/favicon.webp',
				avatar: 'https://library.gxres.net/images/avatars/gxres042.webp',
				archs: ['Nuxt', 'Cloudflare'],
				date: '2025-08-28',
				comment: '前端/网络技术实践与个人记录',
			},
			{
				author: '酥米',
				title: '酥米的小站',
				desc: '终有一日，寻梦中人',
				link: 'https://www.sumi233.top/',
				feed: 'https://www.sumi233.top/atom.xml',
				icon: 'https://www.sumi233.top/favicon.ico',
				avatar: 'https://cdn.sumi233.top/gh/huang233893/blog-image-bed/top/huang233893/imgs/blog/userfb6a1018b84ce485.jpg',
				archs: ['Hexo', '国内 CDN'],
				date: '2025-08-29',
				comment: '计算机网络知识，设备折腾。',
			},
			{
				author: 'kzhik',
				title: 'kzhik\'s website',
				desc: '前端/网络技术实践与个人记录',
				link: 'https://www.kzhik.cn/',
				feed: 'https://www.kzhik.cn/resources/rss.xml',
				icon: 'https://www.kzhik.cn/favicon.ico',
				avatar: 'https://www.kzhik.cn/avatar.webp',
				archs: ['Nuxt', '国内 CDN'],
				date: '2025-08-31',
				comment: '前端/网络技术实践与个人记录',
			},
			{
				author: 'ATao',
				title: 'ATao-Blog',
				desc: '做自己喜欢的事',
				link: 'https://blog.atao.cyou',
				feed: 'https://blog.atao.cyou/atom.xml',
				icon: 'https://cdn.atao.cyou/Web/Avatar.png',
				avatar: 'https://cdn.atao.cyou/Web/Avatar.png',
				archs: ['Nuxt', '服务器'],
				date: '2025-09-09',
				comment: '技术实践与问题解决方案',
			},
			{
				author: '克喵',
				sitenick: '喵落阁',
				title: '喵落阁',
				desc: '愿你看清一切真相后，依旧热爱你的家人和朋友。',
				link: 'https://blog-v3.kemeow.top/',
				feed: 'https://blog-v3.kemeow.top/atom.xml',
				icon: 'https://img.314926.xyz/images/2025/08/13/no-background-kemiaofxjun.webp',
				avatar: 'https://img.314926.xyz/images/2025/08/13/no-background-kemiaofxjun.webp',
				archs: ['Nuxt', 'Vercel'],
				date: '2025-09-11',
				comment: '博客折腾记录、工具/资源网站收集。',
			},
			{
				author: 'fishcpy',
				sitenick: '小破站',
				title: 'fishcpy的小破站',
				desc: '非淡泊无以明志，非宁静无以致远',
				link: 'https://blog.fis.ink/',
				feed: 'https://blog.fis.ink/atom.xml',
				icon: 'https://www.fis.ink/img/logo_c.png',
				avatar: 'https://www.fis.ink/img/logo.png',
				archs: ['Nuxt', '国内 CDN'],
				date: '2025-09-13',
				comment: '博客/服务器技术实践、生活记录、资源分享。',
			},
			{
				author: '鲲',
				title: 'KUN\'s Blog',
				desc: 'KUN\'s moe blog, KUN IS THE CUTEST!',
				link: 'https://soft.moe/',
				feed: 'https://soft.moe/atom.xml',
				icon: 'https://soft.moe/favicon.ico',
				avatar: 'https://soft.moe/avatar.webp',
				archs: ['VitePress', 'Cloudflare'],
				date: '2025-09-13',
				comment: '鲲Gal站长，Nuxt高手，重构博客计划已搁置两年有余。',
			},
			{
				author: '北桥苏',
				sitenick: 'ZERO开发',
				desc: '一个持续探索副业的独立开发者博客',
				link: 'https://www.zerofc.cn/',
				feed: 'https://www.zerofc.cn/atom.xml',
				icon: 'https://www.zerofc.cn/img/favicon.png',
				avatar: 'https://www.zerofc.cn/img/avatar.png',
				archs: ['Hexo', 'GitHub Pages'],
				date: '2025-09-18',
				comment: '技术开发与工具应用。',
			},
			{
				author: 'Refactored',
				title: 'RefactX Project',
				desc: '形体是简单而纯粹的，它不是完整的群体，每个形体都指向其复杂性，并最终被复杂性联系在一起。',
				link: 'https://www.refact.cc/',
				feed: 'https://www.refact.cc/rss.xml',
				icon: 'https://www.refact.cc/favicon.ico',
				avatar: 'https://www.refact.cc/avatar.png',
				archs: ['Astro', 'Vercel'],
				date: '2025-09-22',
				comment: 'RefactX 主题相关介绍、个人思考。',
			},
			{
				author: 'Elykia',
				title: '致以无暇之人',
				desc: '爱莉希雅永远爱你～',
				link: 'https://blog.elykia.cn/',
				feed: 'https://blog.elykia.cn/atom.xml',
				icon: 'https://blog.elykia.cn/favicon.ico',
				avatar: getGhAvatar('elykia-cn'),
				archs: ['Hexo', '国内 CDN'],
				date: '2025-09-26',
				comment: 'Hexo 安知鱼主题美化。',
			},
			{
				author: 'VnYzm',
				title: 'VnYzm的博客',
				desc: '分享技术心得和摸鱼感想',
				link: 'https://zimingyuan.github.io/',
				icon: 'https://zimingyuan.github.io/img/favicon.ico',
				avatar: getGhAvatar('ZimingYuan'),
				archs: ['Python', 'GitHub Pages'],
				date: '2025-10-01',
				comment: '动漫观后感、游戏玩后感、技术笔记。',
			},
		],
	},
	/* ========从此处新增友链======== */
	{
		name: '现实之域',
		desc: '博主们或许正忙着追随生活的烟火气。',
		// @keep-sorted { "keys": ["date"] }
		entries: [
			{
				author: '恩泽',
				sitenick: 'Colsrch',
				title: 'Colsrch的小破站',
				desc: '愿多年以后，我可以酌一杯清酒，烂醉如泥，梦中回到我们的曾经。',
				link: 'https://colsrch.cn/',
				feed: 'https://colsrch.cn/atom.xml',
				icon: getFavicon('colsrch.cn'),
				avatar: 'https://7.isyangs.cn/1/657976c27bea6-1.png',
				archs: ['Hexo', '国内 CDN'],
				date: '2024-02-01',
				comment: '鸽王，去哪里发展了？',
			},
			{
				author: '小李同学',
				sitenick: 'Coding',
				title: '小李同学 Coding',
				desc: '一支努力变强的小彩笔',
				link: 'https://blog.xxfer.cn/',
				feed: 'https://blog.xxfer.cn/rss.xml',
				icon: 'https://www.xxfer.cn/icon.png',
				avatar: getGhAvatar('JJLibra'),
				archs: ['Hexo', '国内 CDN'],
				date: '2024-02-01',
				comment: '瓜大网安学长。',
			},
			{
				author: '桜紺狸',
				sitenick: '部落阁',
				title: '桜紺狸の部落阁',
				desc: '一个闲聊萌新动漫技术交流站',
				link: 'https://www.skira.top/',
				feed: 'https://www.skira.top/feed.xml',
				icon: 'https://www.skira.top/img/skira.ico',
				avatar: 'https://www.skira.top/img/lemonsuka.webp',
				archs: ['Hexo', 'Vercel'],
				date: '2024-02-01',
				comment: '搞机发烧友，小众系统爱好者，前端研究员。',
			},
			{
				author: '茂茂物语',
				desc: '茂茂的成长之路，包含前端常用知识、源码阅读笔记、各种奇淫技巧、日常提效工具等',
				link: 'https://notes.fe-mm.com/',
				icon: getGhIcon('maomao1996'),
				avatar: getGhAvatar('maomao1996'),
				archs: ['VitePress', 'Cloudflare'],
				date: '2024-02-17',
			},
			{
				author: 'Naokuo',
				desc: '请给我来亿碗三鲜面',
				link: 'https://index.naokuo.top/',
				feed: 'https://index.naokuo.top/rss2.xml',
				icon: getFavicon('index.naokuo.top'),
				avatar: 'https://yl2209.github.io/img/favicon.ico',
				archs: ['Hexo', '服务器'],
				date: '2024-02-18',
				comment: '折腾博客。',
			},
			{
				author: '石头',
				sitenick: '铭心石刻',
				title: '铭心石刻',
				desc: '愿岁并谢，与友长兮',
				link: 'https://blog.kouseki.cn/',
				feed: 'https://blog.kouseki.cn/rss.xml',
				icon: 'https://blog.kouseki.cn/favicon.ico',
				avatar: 'https://blog.kouseki.cn/imgs/avatar.webp',
				archs: ['Hexo', 'Vercel'],
				date: '2024-03-01',
				comment: '折腾Hexo博客，友链页面蛮多博客折腾选手的。',
			},
			{
				author: '洛寒兮',
				title: 'I\'m Luochancy',
				desc: '这是个猫猫的博客喵～',
				link: 'https://www.luochancy.com/',
				feed: 'https://www.luochancy.com/feed',
				icon: 'https://www.luochancy.com/wp-content/uploads/2023/10/cropped-231026_head_image-32x32.png',
				avatar: 'https://www.luochancy.com/wp-content/uploads/2023/12/1904634_Ehaif6np.png',
				archs: ['WordPress', 'Cloudflare'],
				date: '2024-03-01',
				comment: '高中生。',
			},
			{
				author: '浪海导航',
				link: 'https://www.langhai.net/',
				icon: 'https://www.langhai.net/assets/images/langhai-logo.png',
				avatar: 'https://www.langhai.net/assets/images/langhai-logo.png',
				archs: ['Hugo', 'Cloudflare'],
				date: '2024-06-04',
			},
			{
				author: '徐徐爱coding',
				desc: '一个精美的个人博客，记录平时的学习笔记',
				link: 'https://www.xu69.com',
				// feed: 'https://www.xu69.com/rss.xml',
				icon: 'https://www.xu69.com/xu-resource/ico.png',
				avatar: getGhAvatar('junxu821'),
				archs: ['Next.js', '服务器'],
				date: '2024-09-01',
				comment: '前端技术笔记，希望能做好响应式。',
			},
			{
				author: '菜园前端',
				desc: '前端学习笔记分享、小白都能看懂的笔记',
				link: 'https://note.noxussj.top/?s=y9',
				icon: 'https://note.noxussj.top/logo.png',
				avatar: getGhAvatar('noxussj2'),
				archs: ['VitePress', '服务器'],
				date: '2024-10-23',
				comment: '前端学习笔记。',
				// error: '2024年12月起无法访问 (504)',
			},
			{
				author: '一粒微尘',
				desc: '撷光以望，纳星于瞳',
				link: 'https://blog.667408.xyz/',
				feed: 'https://blog.667408.xyz/atom.xml',
				icon: getGhIcon('catxian'),
				avatar: getGhAvatar('catxian'),
				archs: ['Hexo', 'Cloudflare'],
				date: '2024-11-07',
				comment: 'Hexo博客折腾，技术分享。',
				error: '域名2025-09-24过期',
			},
		],
	},
	{
		name: '漫游',
		desc: '网上冲浪时发现的精彩内容与常读订阅，与君共享。',
		// @keep-sorted { "keys": ["date"] }
		entries: [
			{
				author: '风记星辰',
				desc: '热爱你来过的每度温暖',
				feed: 'https://www.thyuu.com/feed',
				link: 'https://thyuu.com/',
				icon: 'https://std.thyuu.com/logo.svg',
				avatar: 'https://std.thyuu.com/logo.svg',
				archs: ['WordPress', '服务器'],
				date: '2024-02-01',
			},
			{
				author: 'Randwind',
				title: 'Randwind\'s Blog',
				desc: '你可以期待太阳从东方升起，而风却随心所欲地从四面八方吹来。',
				link: 'https://www.randwind.com/',
				feed: 'https://randwind.com/feed.xml',
				icon: 'https://wsrv.nl/?url=randwind.com/favicon.ico',
				avatar: 'https://wsrv.nl/?url=randwind.com/favicon.ico',
				archs: ['Hugo', 'Cloudflare'],
				date: '2024-02-03',
				comment: '一个喜欢折腾的 Web 前端开发者。2024-05-28 关闭友链功能。',
			},
			{
				author: '静かな森',
				desc: '致虚极，守静笃。',
				link: 'https://innei.in/',
				feed: 'https://innei.in/feed',
				icon: 'https://innei.in/innei.svg',
				avatar: getGhAvatar('Innei'),
				archs: ['Mix Space', 'Cloudflare'],
				date: '2024-02-13',
			},
			{
				author: 'Myth',
				desc: '荒唐无聊正经有趣的大学生 | 业余 Minecraft 腐竹 | PTer',
				title: 'Myth\'s Blog | Myth 的小站',
				link: 'https://myth.cx/',
				feed: 'https://myth.cx/index.xml',
				icon: 'https://myth.cx/favicon.ico',
				avatar: 'https://myth.cx/img/avatar_hu_a008ef868a8cf25a.png',
				archs: ['Hugo', '国内 CDN'],
				date: '2024-04-11',
			},
			{
				author: 'Dejavu',
				title: 'Dejavu\'s Blog',
				link: 'https://blog.dejavu.moe/',
				feed: 'https://blog.dejavu.moe/index.xml',
				icon: 'https://blog.dejavu.moe/images/favicon.png',
				avatar: getGhAvatar('DejavuMoe'),
				archs: ['Hugo', 'Cloudflare'],
				date: '2024-04-29',
			},
			{
				author: '甜鱼',
				sitenick: 'Ayu',
				title: '甜鱼/Ayu',
				desc: '三脚猫多面手，努力学习世界的一切。',
				link: 'https://ayu.land/',
				feed: 'https://ayu.land/rss.zh.xml',
				icon: 'https://ayu.land/bin/favicon.png',
				avatar: 'https://ayu.land/favicon.png',
				archs: ['HTML', 'Deno Deploy'],
				date: '2024-10-26',
			},
			{
				author: 'Anthony Fu',
				desc: 'Hey, I am Anthony Fu, a fanatical open sourceror.',
				link: 'https://antfu.me/',
				feed: 'https://antfu.me/feed.xml',
				icon: 'https://antfu.me/favicon.svg',
				avatar: getGhAvatar('antfu'),
				archs: ['Vue', 'Netlify'],
				date: '2024-10-26',
			},
			{
				author: '無名',
				sitenick: '小栈',
				title: '無名小栈',
				desc: '分享技术与科技生活',
				link: 'https://blog.imsyy.top/',
				feed: 'https://blog.imsyy.top/rss.xml',
				icon: getFavicon('blog.imsyy.top'),
				avatar: getGhAvatar('imsyy'),
				archs: ['VitePress', 'Vercel'],
				date: '2024-10-26',
			},
			{
				author: '汐笺',
				sitenick: '最小可读',
				desc: '基本无害，可能有用',
				link: 'https://mvread.blog/',
				feed: 'https://mvread.blog/feed',
				icon: 'https://wsrv.nl/?url=mmbiz.qpic.cn/mmbiz_png/ObdOUIBwLwlt7jrOzKib6gUM83iaY6d6qLF4fH7AtAyL8mnic0jPicnFLdjXnduL5Pkj8Viah8RJAZzPwOWlj8995Qw/0',
				avatar: 'https://cdnv2.ruguoapp.com/FufBpXB3Ax66mh9vkBEjTujMVLmPv3.jpg?imageMogr2/auto-orient/heic-exif/1/format/jpeg/thumbnail/!300x300r/gravity/Center/crop/!300x300a0a0',
				archs: ['WordPress', 'Cloudflare'],
				date: '2024-10-29',
			},
			{
				author: 'PlatyHsu',
				sitenick: 'neverland',
				desc: 'Editor. Currently at SSPAI.',
				link: 'https://hsu.cy/',
				feed: 'https://hsu.cy/feed.xml',
				icon: getFavicon('hsu.cy'),
				avatar: 'https://cdnfile.sspai.com/2024/01/19/2e1141e8de2022c94ea9dd8b805f877c.png?imageMogr2/auto-orient/thumbnail/!200x200r/gravity/center/crop/200x200/format/webp/ignore-error/1',
				archs: ['Hugo', 'Cloudflare'],
				date: '2025-09-03',
				comment: '长期记录多领域内容，涵盖数码产品软件配置、文艺作品品论等，兼具技术实践与观点分享。',
			},
		],
	},
] satisfies FeedGroup[]
