import type { FeedGroup } from '~/types/feed'
import { getFavicon, getGhAvatar, getGhIcon, getQqAvatar, QqAvatarSize } from './utils/img'

export default [
	{
		name: '相谈甚多',
		desc: '',
		// @keep-sorted { "keys": ["date"] }
		entries: [
			{
				author: 'LineXic',
				sitenick: '书屋',
				title: 'LineXic书屋',
				desc: '难离难舍，想抱紧些。',
				link: 'https://www.linexic.top',
				feed: 'https://www.linexic.top/rss.xml',
				icon: getFavicon('www.linexic.top'),
				avatar: getGhAvatar('linexic'),
				archs: ['Astro', 'Netlify'],
				date: '2025-01-24',
				comment: '交流技术，学习前端时经常鼓励我。',
			},
		],
	},
	{
		name: '站友',
		desc: '哔——啵——电波通讯中，欢迎常来串台～',
		// @keep-sorted { "keys": ["date"] }
		entries: [
			{
				author: '枫落丰源',
				desc: '和你的日常，就是奇迹',
				link: 'https://blog.feng1026.top',
				feed: 'https://blog.feng1026.top/rss.xml',
				// icon: getFavicon('blog.feng1026.top'),
				icon: 'https://blog.feng1026.top/favicon/favicon.png',
				avatar: getGhAvatar('Qiufengluoyes'),
				archs: ['Astro', 'Cloudflare'],
				date: '2025-01-24',
				comment: '生活随笔。',
			},
			{
				author: 'MeowcoQAQ',
				title: 'MeowcoQAQ\'s Blog',
				desc: '还是音 MIDI 大佬',
				link: 'https://blog.mcneko.com',
				feed: 'https://blog.mcneko.com/feed',
				// icon: getFavicon('blog.mcneko.com'),
				icon: 'https://blog.mcneko.com/wp-content/uploads/2024/07/cropped-openaiassets_676d2e034bcb92cbea60e4faf5fd7985_2579861715703792700-1-32x32.png',
				avatar: getGhAvatar('nkqa'),
				archs: ['WordPress', '服务器'],
				date: '2025-01-24',
				comment: '分享内容与琐事。',
			},
			{
				author: 'Steven',
				title: 'Steven\'s Blog',
				desc: '没有既定的终点，只有无限的探索',
				link: 'https://blog.stevenw.cc',
				feed: 'https://blog.stevenw.cc/rss.xml',
				icon: getGhIcon('Steven-WZH'),
				avatar: getGhAvatar('Steven-WZH'),
				archs: ['Halo', 'Cloudflare'],
				date: '2025-02-07',
				comment: '分享折腾经历，目前文章停更。',
			},
			{
				author: 'xzadudu179',
				sitenick: '小窝',
				title: 'XME Notes Library',
				desc: 'xzadudu179的小窝',
				link: 'https://blog.xzadudu179.top',
				feed: 'https://blog.xzadudu179.top/atom.xml',
				icon: getFavicon('blog.xzadudu179.top'),
				avatar: getGhAvatar('xzadudu179'),
				archs: ['Hexo', 'Vercel'],
				date: '2025-04-19',
				comment: '好看的博客主题，期待更多文章。',
			},
			{
				author: 'damesck',
				sitenick: '小屋',
				title: 'damesck的小屋',
				desc: '致不完美的明天_',
				link: 'https://damesck.net',
				feed: 'https://blog.damesck.net/index.php/feed/',
				icon: getFavicon('blog.damesck.net'),
				avatar: getGhAvatar('damesck233'),
				archs: ['Typecho', 'Cloudflare'],
				date: '2025-05-09',
				comment: '这是怕坛大妈。',
			},
			{
				author: 'Adpro',
				title: 'AdproのBlog',
				desc: 'Adpro的Blog，可能有有用的东西？',
				link: 'https://blog.adproqwq.top',
				feed: 'https://blog.adproqwq.top/atom.xml',
				// icon: getFavicon('blog.adproqwq.top'),
				icon: 'https://blog.adproqwq.top/avatar.jpg',
				avatar: getGhAvatar('adproqwq'),
				archs: ['Vue', 'Vercel'], // 并不准确
				date: '2025-07-25',
				comment: '业余前端开发，维护着各类好东西。',
			},
		],
	},
	/* {
		name: '慢请求',
		desc: '监听频率降低',
		// @keep-sorted { "keys": ["date"] }
		entries: [
		],
	}, */
	{
		name: '参考',
		desc: '感谢热爱分享的每个人。',
		// @keep-sorted { "keys": ["date"] }
		entries: [
			{
				author: '纸鹿',
				sitenick: '摸鱼处',
				title: '纸鹿摸鱼处',
				desc: '纸鹿至麓不知路，支炉制露不止漉',
				feed: 'https://blog.zhilu.site/atom.xml',
				link: 'https://blog.zhilu.site',
				icon: getFavicon('blog.zhilu.site'),
				avatar: getGhAvatar('L33Z22L11'),
				archs: ['Nuxt', 'Vercel'],
				date: '2025-03-23',
				comment: '技术以及文笔参考（博客主题原作者）',
			},
			{
				author: 'Alex John',
				title: ' Alex John\'Blog',
				link: 'https://hdalex.top',
				// icon: getFavicon('hdalex.top'),
				icon: 'https://hdalex.top/favicon.ico',
				avatar: getGhAvatar('13RTK'),
				archs: ['Nuxt', 'Cloudflare'],
				date: '2025-07-26',
				comment: '全栈路线参考',
			},
			{
				author: 'Hans',
				sitenick: '札记',
				title: '计算机技术学习札记',
				feed: 'https://www.criwits.top/index.xml',
				link: 'https://www.criwits.top',
				icon: 'https://www.criwits.top/images/favicon.ico',
				avatar: getGhAvatar('criwits'),
				archs: ['Hugo', 'GitHub Pages'],
				date: '2025-08-02',
				comment: '电脑使用参考',
			},
		],
	},
] satisfies FeedGroup[]
