import type { FeedGroup } from '~/types/feed'
import { getGhAvatar } from './utils/img'

export default [{
	name: '相谈甚多',
	desc: '',
	entries: [{
		author: 'LineXic',
		sitenick: '书屋',
		title: 'LineXic书屋',
		desc: '难离难舍，想抱紧些。',
		link: 'https://www.linexic.top',
		feed: 'https://www.linexic.top/rss.xml',
		icon: 'https://www.linexic.top/logo.png',
		avatar: getGhAvatar('linexic'),
		archs: ['Astro', 'Netlify'],
		date: '2025-01-24',
		comment: '技术分享，高中生活。',
	}],
}, {
	name: '站友同好',
	desc: '哔——啵——电波通讯中，欢迎常来串台~',
	entries: [{
		author: '枫落丰源',
		desc: '和你的日常，就是奇迹',
		link: 'https://blog.feng1026.top',
		feed: 'https://blog.feng1026.top/rss.xml',
		icon: 'https://blog.feng1026.top/favicon/favicon.png',
		avatar: getGhAvatar('Qiufengluoyes'),
		archs: ['Astro', 'Vercel'],
		date: '2025-01-24',
		// comment: '生活随笔。',
	}, {
		author: 'MeowcoQAQ',
		title: 'MeowcoQAQ\'s Blog',
		desc: '还是音 MIDI 大佬',
		link: 'https://blog.mcneko.com',
		feed: 'https://blog.mcneko.com/feed',
		icon: 'https://blog.mcneko.com/wp-content/uploads/2024/07/cropped-openaiassets_676d2e034bcb92cbea60e4faf5fd7985_2579861715703792700-1-32x32.png',
		avatar: getGhAvatar('nkqa'),
		archs: ['WordPress', 'Cloudflare'],
		date: '2025-01-24',
		comment: '分享内容与琐事。',
	}, {
		author: 'Steven',
		title: 'Steven\'s Blog',
		desc: '没有既定的终点，只有无限的探索',
		link: 'https://blog.stevenw.cc',
		feed: 'https://blog.stevenw.cc/rss.xml',
		icon: 'https://blog.stevenw.cc/upload/logo.ico',
		avatar: getGhAvatar('Steven-WZH'),
		archs: ['Halo', 'Cloudflare'],
		date: '2025-02-07',
		comment: 'MC同好，文章停更。',
	}, {
		author: 'xzadudu179',
		sitenick: '小窝',
		title: 'XME Notes Library',
		desc: 'xzadudu179的小窝',
		link: 'https://blog.xzadudu179.top',
		feed: 'https://blog.xzadudu179.top/atom.xml',
		icon: 'https://image.179.life/images/icon.ico',
		avatar: getGhAvatar('xzadudu179'),
		archs: ['Hexo', 'Vercel'],
		date: '2025-04-19',
		comment: '异次元旅行到的博客，好看。',
	}, {
		author: 'damesck',
		sitenick: '小屋',
		title: 'damesck的小屋',
		desc: '致不完美的明天_',
		link: 'https://damesck.net',
		feed: 'https://blog.damesck.net/index.php/feed/',
		icon: 'https://damesck.net/logo.png',
		avatar: getGhAvatar('damesck233'),
		archs: ['Typecho', 'Cloudflare'],
		date: '2025-05-09',
		comment: '怕坛大妈。',
	}, {
		author: 'Adpro',
		title: 'AdproのBlog',
		desc: 'Adpro的Blog，可能有有用的东西？',
		link: 'https://blog.adproqwq.top',
		feed: 'https://blog.adproqwq.top/atom.xml',
		icon: 'https://blog.adproqwq.top/avatar.jpg',
		avatar: getGhAvatar('adproqwq'),
		archs: ['Vue', 'GitHub Pages'], // 并不准确
		date: '2025-07-25',
	}],
}] satisfies FeedGroup[]
