import type { FeedGroup } from '~/types/feed'
import { getGhAvatar } from './utils/img'

export default [{
	name: '参考',
	desc: '有所启发，感谢分享。',
	entries: [{
		author: '摆烂梦',
		sitenick: '小窝',
		title: '梦的小窝',
		desc: '皮下三寸皆白骨',
		link: 'https://blog.xmcyh.cn',
		feed: 'https://blog.xmcyh.cn/index.php/feed/',
		icon: 'https://s.nmxc.ltd/sakurairo_vision/@2.6/basic/favicon.ico',
		avatar: 'https://weavatar.com/avatar/e070ca1b761683c868d2ceffb5345c24c9cf52961f094964947673f7502c21e5?d=blank&s=92',
		archs: ['WordPress', '服务器'],
		date: '2024-04-13',
		comment: '特此致谢梦云机主。',
		error: '证书过期',
	}, {
		author: '纸鹿',
		sitenick: '摸鱼处',
		title: '纸鹿摸鱼处',
		desc: '纸鹿至麓不知路，支炉制露不止漉',
		feed: 'https://blog.zhilu.site/atom.xml',
		link: 'https://blog.zhilu.site',
		icon: 'https://www.zhilu.site/icon.png',
		avatar: getGhAvatar('L33Z22L11'),
		archs: ['Nuxt', 'Vercel'],
		date: '2025-03-23',
		comment: '文笔参考（博客主题原作者）',
	}, {
		author: 'Alex John',
		title: ' Alex John\'Blog',
		link: 'https://hdalex.top',
		icon: 'https://hdalex.top/favicon.ico',
		avatar: getGhAvatar('13RTK'),
		archs: ['Nuxt', 'Cloudflare'],
		date: '2025-07-26',
		comment: '全栈路线参考',
	}, {
		author: 'Hans',
		sitenick: '札记',
		title: '计算机技术学习札记',
		feed: 'https://www.criwits.top/index.xml',
		link: 'https://www.criwits.top',
		icon: 'https://www.criwits.top/images/favicon.ico',
		avatar: getGhAvatar('criwits'),
		archs: ['Hugo', 'GitHub Pages'],
		date: '2025-08-02',
		comment: '电脑使用参考',
	}],
}] satisfies FeedGroup[]
