import type { FriendGroup } from '~/types/friend'

export default <FriendGroup[]> [
    {
        name: '大佬们',
        desc: 'Xlenco在网络上认识的大佬。',
        items: [
            {
                name: '张洪Heo',
                desc: '分享设计与科技生活',
                link: 'https://blog.zhheo.com/',
                icon: 'https://bu.dusays.com/2022/12/28/63ac2812183aa.png',
                archs: ['Hexo', 'CDN (国内)'],
                date: '2024-02-02',
                comment: '知名博主，其博客设计风格被众多人借鉴。',
            },            
            {
                name: 'Leonus',
                desc: '进一寸有进一寸的欢喜',
                link: 'https://blog.leonus.cn/',
                icon: 'https://q1.qlogo.cn/g?b=qq&nk=553344777&s=5',
                archs: ['Hexo', 'CDN (国内)'],
                date: '2024-10-03',
                comment: '用Butterfly主题时遇到的大佬。',
            },  
            {
                name: 'Akilar',
                desc: '欢迎光临糖果屋',
                link: 'https://akilar.top/',
                icon: 'https://npm.elemecdn.com/akilar-candyassets/image/siteicon/favicon.png',
                archs: ['Hexo', 'CDN (国内)'],
                date: '2024-10-03',
                comment: '糖果屋的建立者，被网友称为‘店长’。', 
            }, 
            {
                name: '纸鹿本鹿',
                desc: '纸鹿至麓不知路，支炉制露不止漉',
                link: 'https://blog.zhilu.cyou/',
                icon: 'https://wsrv.nl/?url=github.com/L33Z22L11.png',
                archs: ['Hexo', 'Vercel'],
                date: '2024-10-03',
                comment: '本博客的编写者',
            },
            {
                name: 'Zkeq の Coding 日志',
                desc: '自强，弘毅，求实',
                link: 'https://icodeq.com/',
                icon: 'https://img.onmicrosoft.cn/Avatar.jpg',
                archs: ['Hexo', 'Vercel'],
                date: '2024-10-03',
                comment: '之前认识的前端大佬',
            },              
        ],
    },
    {
        name: '网上邻居',
        desc: '哔——啵——电波通讯中，欢迎常来串门。',
        items: [
            {
                name: '陈鑫磊Blog',
                desc: '这个人太懒了啥也没写......',
                link: 'https://www.cxl2020mc.top',
                icon: 'https://www.cxl2020mc.top/img/avatar.png',
                archs: ['Hexo', 'Vercel'],
                date: '2024-10-03',
            },
            {
                name: '天翔TNXG',
                title: '空间站',
                desc: '明日尚未到来，希望凝于心上',
                link: 'https://tnxgmoe.com/',
                icon: 'https://api-space.tnxg.top/avatar?s=qq',
                archs: ['Mix Space', 'Cloudflare'],
                date: '2024-07-11',
                comment: '西北地区高中生，开源爱好者。',
            }, 
            {
                name: '葱苓samaの博客',
                desc: "Don't worry, Be happy.",
                link: 'https://blog.ciraos.top/',
                icon: 'https://blog.ciraos.top/custom/avatar1.avif ',
                archs: ['Hexo', 'CDN (国内)'],
                date: '2024-10-03',
            },  
            {
                name: '知行博客',
                desc: 'Java开发代码实战，搜你所需，快速CV，早点下班～',
                link: 'https://zxalive.com/',
                icon: 'https://zxalive.com/avatar.webp',
                archs: ['Halo', 'CDN (国内)'],
                date: '2024-10-03',
            },
            {
                name: 'Liu Zijian’s Blog',
                desc: '道阻且长，行则将至',
                link: 'https://blog.liuzijian.com',
                icon: 'https://blog.liuzijian.com/img/logo.jpg',
                archs: ['Hexo', 'CDN (国内)'],
                date: '2024-10-26',
            },              
        ],
    },
    {
        name: '漫游',
        desc: '网上冲浪时发现的精彩内容，与君共享。',
        items: [
            {
                name: '静かな森',
                link: 'https://innei.in/',
                icon: 'https://wsrv.nl/?url=github.com/Innei.png',
                archs: ['Mix Space', 'Cloudflare'],
                date: '2024-02-13',
            },
        ],
    },
]
