import type { LinkGroup } from '~/types/friend'

export default <LinkGroup[]>[
    {
        name: '朋友',
        desc: '纸鹿和朋友在现实生活中关系很好。虽然他们可能在互联网上不太活跃。',
        items: [
            { name: 'GuuGuai', link: 'https://gug.thisis.host/', icon: 'https://cdn.libravatar.org/avatar/646331bff8f19a0e05679c3cc0fc54d6?s=160' },
            { name: '·半岛的孤城', link: 'https://www.bandao.ltd/', icon: 'https://www.bandao.ltd/wp-content/uploads/corepress_avatar/1.jpg' },
            { name: 'Colsrch', link: 'https://colsrch.cn/', icon: 'https://7.isyangs.cn/1/657976c27bea6-1.png' },
            { name: 'isYangs', link: 'https://www.isyangs.cn/', icon: 'https://7.isyangs.cn/8/655c9835780a0-8.jpg' },
            { name: '学习爱我', link: 'https://studyinglover.com/', icon: 'https://proxy.thisis.plus/favicon.ico' },
            // { name: '·JiaHuann', link: 'https://jiahuann.thisis.host', icon: 'https://wsrv.nl/?url=github.com/JiaHuann.png' },
            { name: 'Yuanfang', link: 'https://yuanfang.thisis.host/', icon: 'https://wsrv.nl/?url=github.com/zhendewokusi.png' },
            { name: 'Ph0m', link: 'https://blog.phom.space/', icon: 'https://pic.imgdb.cn/item/65e1df0c9f345e8d03bcdd6a.png' },
            { name: 'Future', link: 'https://future.thisis.host/', icon: 'https://wsrv.nl/?url=github.com/SIMple-lives.png' },
            { name: '·Yuanmxc', link: 'https://yuanmxc.site/', icon: 'https://wsrv.nl/?url=github.com/Yuanmxc.png' },
            { name: 'Tiny-Sky', link: 'https://tiny-sky.github.io/', icon: 'https://wsrv.nl/?url=github.com/tiny-sky.png' },
            { name: 'Shawn', link: 'https://shawn.thisis.host/', icon: 'https://wsrv.nl/?url=github.com/ShawnJeffersonWang.png' },
            { name: 'Kayle', link: 'https://www.kayle7.top/', icon: 'https://q1.qlogo.cn/g?b=qq&nk=1239625475&s=4' },
            { name: '桃林饮酒', link: 'https://www.taolin.site/', icon: 'https://q1.qlogo.cn/g?b=qq&nk=2389183644&s=4' },
            { name: 'Magic462', link: 'https://magic.thisis.host/', icon: 'https://q1.qlogo.cn/g?b=qq&nk=1623728267&s=4' },
            { name: 'fault123', link: 'https://fault.thisis.host/', icon: 'https://q1.qlogo.cn/g?b=qq&nk=2444073573&s=4' },
            { name: 'Monoceros406', link: 'https://monoceros406.github.io/', icon: 'https://q1.qlogo.cn/g?b=qq&nk=1295625063&s=4' },
        ],
    },
    {
        name: '网上邻居',
        desc: '哔——啵——电波通讯中，欢迎常来串门。',
        items: [
            { name: '张洪Heo', link: 'https://blog.zhheo.com/', icon: 'https://bu.dusays.com/2022/12/28/63ac2812183aa.png' },
            { name: '斬風·千雪', link: 'https://blog.chyk.ink/', icon: 'https://q1.qlogo.cn/g?b=qq&nk=3526514925&s=4' },
            { name: '微光档案', link: 'https://bikari.top/', icon: 'https://cdn.libravatar.org/avatar/ecb2ea87c4532f007838d86d02798f89?s=160' },
            { name: 'Revincx', link: 'https://blog.revincx.icu/', icon: 'https://weavatar.com/avatar/20eed6a268787c9a751165bc1ec56e90' },
            { name: '小李同学', link: 'https://blog.xxfer.cn/', icon: 'https://picsur.xxfer.cn/i/7303d79e-4736-41cf-b14f-d2b5597ad29b.webp' },
            { name: '铭心石刻', link: 'https://blog.kouseki.cn/', icon: 'https://blog.kouseki.cn/imgs/avatar.webp' },
            { name: '桜紺狸', link: 'https://www.skira.top/', icon: 'https://www.skira.top/img/lemonsuka.webp' },
            { name: 'Yunyi', link: 'https://www.yunyitang.me/', icon: 'https://www.yunyitang.me/img/Avatar.png' },
            { name: 'L1nSn0w', link: 'https://blog.linsnow.cn/', icon: 'https://blog.linsnow.cn/img/avatar.png' },
            { name: 'Naokuo', link: 'https://www.naokuo.top/', icon: 'https://cdn.cbd.int/naokuo-blog/img/about/avatar-512x512.png' },
            { name: '晓空', link: 'https://blog.moeworld.tech/', icon: 'https://blog.moeworld.tech/wp-content/themes/kratos-pjax-master/static/images/photo.jpg' },
            { name: 'Kegongteng', link: 'https://kegongteng.cn/', icon: 'https://bu.dusays.com/2023/12/23/65867c3357bb6.jpg' },
            { name: '洛寒兮', link: 'https://www.luochancy.com/', icon: 'https://www.luochancy.com/wp-content/uploads/2023/12/1904634_Ehaif6np.png' },
            { name: '清羽飞扬', link: 'https://blog.qyliu.top/', icon: 'https://blog.qyliu.top/info/avatar.ico' },
            { name: '呓语梦轩', link: 'https://blog.awaae001.top/', icon: 'https://image.m-c.top/?/images/2024/01/13/Pqeh0v6VaK/ico.jpg' },
            { name: 'Lafcadia', link: 'https://chuishen.xyz/', icon: 'https://cravatar.cn/avatar/57ff1222a81493a0e72782530e77b269?s=160' },
            { name: '晚夜', link: 'https://www.iczrx.cn/', icon: 'https://q1.qlogo.cn/g?b=qq&nk=1463656527&s=4' },
            { name: '春日心动日记', link: 'https://blog.mletter.cn/', icon: 'https://img13.360buyimg.com/ddimg/jfs/t1/239095/17/9691/19853/664d82dfF34a0990c/c4198876146be2d4.jpg' },
            { name: '天翔TNXG', link: 'https://tnxgmoe.com/', icon: 'https://api-space.tnxg.top/avatar?s=qq' },
            { name: 'Ariasaka', link: 'https://blog.yaria.top/', icon: 'https://weavatar.com/avatar/795ce413eb6c7485954b78283ffa3e00?s=160' },
            { name: '365云栈', link: 'https://blog.365sites.top/', icon: 'https://blog.365sites.top/upload/avatar.png' },
            { name: 'FloatSheep', link: 'https://blog.hesiy.cn', icon: 'https://wsrv.nl/?url=github.com/FloatSheep.png' },
            { name: 'Henry Moreau', link: 'https://blog.henrywhu.cn/', icon: 'https://bu.dusays.com/2024/06/28/667e684e0adbe.png' },
            { name: 'Xlenco', link: 'https://blog.xlenco.top/', icon: 'https://q1.qlogo.cn/g?b=qq&nk=1043865083&s=4' },
            { name: '十玖八柒', link: 'https://blog.ahzoo.cn/', icon: 'https://blog.ahzoo.cn/avatar.webp' },
        ],
    },
    {
        name: '漫游',
        desc: '网上冲浪时发现的精彩内容，与君共享。',
        items: [
            { name: '风记星辰', link: 'https://thyuu.com/', icon: 'https://std.thyuu.com/logo.svg' },
            { name: '静かな森', link: 'https://cn.innei.ren/', icon: 'https://wsrv.nl/?url=github.com/Innei.png' },
            { name: '茂茂物语', link: 'https://notes.fe-mm.com/', icon: 'https://notes.fe-mm.com/logo.png' },
            { name: 'Randwind', link: 'https://www.randwind.com/', icon: 'https://wsrv.nl/?url=randwind.com/favicon.ico' },
            { name: 'Myth', link: 'https://myth.cx/', icon: 'https://myth.cx/img/avatar_hu4881e27882f65e048194c2e8319e9874_294915_300x0_resize_box_3.png' },
            { name: 'Dejavu', link: 'https://blog.dejavu.moe/', icon: 'https://blog.dejavu.moe/img/avatar_hu153f535f3685d84c2248f9e3bcb0c932_112544_288x288_fill_q75_h2_box_center_2.webp' },
            { name: '浪海导航', link: 'https://www.langhai.net/', icon: 'https://www.langhai.net/assets/images/langhai-logo.png' },
        ],
    },
]
