import type { FriendGroup } from '~/types/friend'

export default <FriendGroup[]>[
    {
        name: '朋友',
        desc: '纸鹿和朋友在现实生活中关系很好。虽然他们可能在互联网上不太活跃。',
        items: [
            {
                name: 'GuuGuai',
                title: '杂记本',
                desc: '一个什么都可能会写的博客',
                link: 'https://gug.thisis.host/',
                icon: 'https://cdn.libravatar.org/avatar/646331bff8f19a0e05679c3cc0fc54d6?s=160',
                archs: ['Hexo', 'Netlify'],
                date: '2024-01-29',
                comment: '高中同学，技术好友，爱好番剧/折腾。',
            },
            {
                name: '·半岛的孤城',
                title: '小屋',
                link: 'https://www.bandao.ltd/',
                icon: 'https://www.bandao.ltd/wp-content/uploads/corepress_avatar/1.jpg',
                archs: ['Typecho', 'Server'],
                date: '2024-02-02',
                comment: '大学学长，爱好摄影/听歌，会一些Vue。',
            },
            {
                name: 'Colsrch',
                title: '小破站',
                desc: '愿多年以后，我可以酌一杯清酒，烂醉如泥，梦中回到我们的曾经。',
                link: 'https://colsrch.cn/',
                archs: ['Hexo', 'CDN (国内)'],
                icon: 'https://7.isyangs.cn/1/657976c27bea6-1.png',
                date: '2024-02-01',
            },
            {
                name: 'isYangs',
                desc: '一个前端Bug构造师的博客',
                link: 'https://www.isyangs.cn/',
                icon: 'https://7.isyangs.cn/8/655c9835780a0-8.jpg',
                archs: ['Vue', 'CDN (国内)'],
                date: '2024-01-29',
                comment: '高中时认识的小学校友，目前从事前端开发。',
            },
            {
                name: '学习爱我',
                title: 'Studio',
                desc: '要偷偷努力，下回惊艳所有人',
                link: 'https://studyinglover.com/',
                icon: 'https://proxy.thisis.plus/favicon.ico',
                archs: ['Hexo', 'Cloudflare'],
                date: '2024-02-03',
                comment: '“学习哥”',
            },
            // {
            //     name: '·JiaHuann',
            //     link: 'https://jiahuann.thisis.host',
            //     icon: 'https://wsrv.nl/?url=github.com/JiaHuann.png',
            //     archs: ['Hexo', 'Cloudflare'],
            //     comment: '学长，从事eBPF方向。',
            //     date: '2024-02-02',
            // },
            {
                name: 'Yuanfang',
                desc: '琼楼挂月钓流云，梦里瑶台暂借春',
                link: 'https://yuanfang.thisis.host/',
                icon: 'https://wsrv.nl/?url=github.com/zhendewokusi.png',
                archs: ['Hexo', 'Netlify'],
                date: '2024-01-29',
                comment: '大学同级，Linux内核学习中。',
            },
            {
                name: 'Ph0m',
                title: 'Space',
                desc: '好好生活 慢慢相遇',
                link: 'https://blog.phom.space/',
                icon: 'https://pic.imgdb.cn/item/65e1df0c9f345e8d03bcdd6a.png',
                archs: ['Hexo', 'Netlify'],
                date: '2024-03-02',
                comment: '大学学弟。',
            },
            {
                name: 'Future',
                desc: 'Hang on to your dreams!',
                link: 'https://future.thisis.host/',
                icon: 'https://wsrv.nl/?url=github.com/SIMple-lives.png',
                archs: ['Hexo', 'Cloudflare'],
                date: '2024-03-10',
                comment: '大学学弟。',
            },
            {
                name: 'Tiny-Sky',
                desc: '人生苦短，及时行乐',
                link: 'https://tiny-sky.github.io/',
                icon: 'https://wsrv.nl/?url=github.com/tiny-sky.png',
                archs: ['Hexo', 'GitHub Pages'],
                date: '2024-04-03',
                comment: '大学同级，数据库学习中。',
            },
            {
                name: 'Shawn',
                title: '笔记',
                desc: 'Where there is a will, there is a way.',
                link: 'https://shawn.thisis.host/',
                icon: 'https://wsrv.nl/?url=github.com/ShawnJeffersonWang.png',
                archs: ['Hexo', 'Cloudflare'],
                date: '2024-06-13',
                comment: '大学同级，Golang 学习中。',
            },
            {
                name: 'Kayle',
                title: '小站',
                desc: '正在学习嵌入式',
                link: 'https://www.kayle7.top/',
                icon: 'https://q1.qlogo.cn/g?b=qq&nk=1239625475&s=4',
                archs: ['Hexo', 'Cloudflare'],
                date: '2024-06-27',
                comment: '大学同级，嵌入式学习中。',
            },
            {
                name: '桃林饮酒',
                desc: '回不去的何止时间',
                link: 'https://www.taolin.site/',
                icon: 'https://q1.qlogo.cn/g?b=qq&nk=2389183644&s=4',
                archs: ['Astro', 'Vercel'],
                date: '2024-07-16',
                comment: '大学同级，嵌入式学习中。',
            },
            {
                name: 'Magic462',
                desc: '我知我喜乐，纵情跋涉。',
                link: 'https://magic.thisis.host/',
                icon: 'https://q1.qlogo.cn/g?b=qq&nk=1623728267&s=4',
                archs: ['Hexo', 'Cloudflare'],
                date: '2024-07-22',
                comment: '大学学妹，前端学习中。',
            },
            {
                name: 'fault123',
                desc: '学习！学习！还是学习！当然也是要吃点好东西！',
                link: 'https://fault.thisis.host/',
                icon: 'https://q1.qlogo.cn/g?b=qq&nk=2444073573&s=4',
                archs: ['Hexo', 'Netlify'],
                date: '2024-07-29',
                comment: '大学同级，网安学习中。',
            },
            {
                name: 'Monoceros406',
                desc: 'Reverse - 智邮普创工作室安全组/Nepnep联合战队',
                link: 'https://monoceros406.github.io/',
                icon: 'https://q1.qlogo.cn/g?b=qq&nk=1295625063&s=4',
                archs: ['Hexo', 'GitHub Pages'],
                date: '2024-07-29',
                comment: '大学学弟，网安Reverse学习中。',
            },
        ],
    },
    {
        name: '网上邻居',
        desc: '哔——啵——电波通讯中，欢迎常来串门。',
        items: [
            {
                name: '张洪Heo',
                desc: '分享设计与科技生活',
                link: 'https://blog.zhheo.com/',
                icon: 'https://bu.dusays.com/2022/12/28/63ac2812183aa.png',
                archs: ['Hexo', 'CDN (国内)'],
                date: '2024-02-02',
                comment: '知名博主，其博客设计风格被众多人借鉴。',
            },
            {
                name: '斬風·千雪',
                title: '風雪城',
                desc: '浩繁星空下的一场稚嫩的梦',
                link: 'https://blog.chyk.ink/',
                icon: 'https://q1.qlogo.cn/g?b=qq&nk=3526514925&s=4',
                archs: ['Hexo', 'Vercel'],
                date: '2024-03-03',
                comment: 'Archlinux，折腾，大学生。',
            },
            {
                name: 'KazariEX',
                title: '微光档案',
                desc: '虚幻的幸福',
                link: 'https://bikari.top/',
                icon: 'https://cdn.libravatar.org/avatar/ecb2ea87c4532f007838d86d02798f89?s=160',
                archs: ['Nuxt', 'Server'],
                date: '2024-01-30',
                comment: '“四邮四电”直系学长，Vue相关开发者，前端方面指引我不少。',
            },
            {
                name: 'Revincx',
                title: '小破站',
                link: 'https://blog.revincx.icu/',
                icon: 'https://weavatar.com/avatar/20eed6a268787c9a751165bc1ec56e90',
                archs: ['Hexo', 'Vercel'],
                date: '2024-02-05',
                comment: '折腾。',
            },
            {
                name: '小李同学',
                title: 'Coding',
                desc: '一支努力变强的小彩笔',
                link: 'https://blog.xxfer.cn/',
                icon: 'https://picsur.xxfer.cn/i/7303d79e-4736-41cf-b14f-d2b5597ad29b.webp',
                archs: ['Hexo', 'CDN (国内)'],
                date: '2024-02-01',
                comment: '瓜大网安学长。',
            },
            {
                name: '石头',
                title: '铭心石刻',
                desc: '愿岁并谢，与友长兮',
                link: 'https://blog.kouseki.cn/',
                icon: 'https://blog.kouseki.cn/imgs/avatar.webp',
                archs: ['Hexo', 'CDN (国内)'],
                date: '2024-03-01',
                comment: '折腾Hexo博客，友链页面蛮多博客折腾选手的。',
            },
            {
                name: '桜紺狸',
                title: '部落阁',
                desc: '一个闲聊萌新动漫技术交流站',
                link: 'https://www.skira.top/',
                icon: 'https://cravatar.cn/avatar/ee5587c9e699db413647e91d3627846c',
                archs: ['Hexo', 'Vercel'],
                date: '2024-02-01',
                comment: '搞机发烧友，小众系统爱好者，前端研究员。',
            },
            {
                name: 'Yunyi',
                desc: '得闲饮茶~~~',
                link: 'https://www.yunyitang.me/',
                icon: 'https://www.yunyitang.me/img/Avatar.png',
                archs: ['Hexo', 'GitHub Pages'],
                date: '2024-02-18',
                comment: '很有博客的味道。',
            },
            {
                name: 'L1nSn0w',
                desc: '无限进步.🎈',
                link: 'https://linsnow.cn/',
                icon: 'https://wsrv.nl/?url=github.com/lin-snow.png',
                archs: ['Hugo', 'Server'],
                date: '2024-02-14',
                comment: '广工学弟。',
            },
            {
                name: '茂茂物语',
                desc: '茂茂的成长之路，包含前端常用知识、源码阅读笔记、各种奇淫技巧、日常提效工具等',
                link: 'https://notes.fe-mm.com/',
                icon: 'https://notes.fe-mm.com/logo.png',
                archs: ['VitePress', 'Netlify'],
                date: '2024-02-17',
            },
            {
                name: 'Naokuo',
                desc: '请给我来亿碗三鲜面',
                link: 'https://www.naokuo.top/',
                icon: 'https://cdn.cbd.int/naokuo-blog/img/about/avatar-512x512.png',
                archs: ['Hexo', 'Netlify'],
                date: '2024-02-18',
                comment: '折腾博客。',
            },
            {
                name: '晓空',
                title: '空域',
                desc: '探索更大的世界',
                link: 'https://blog.moeworld.tech/',
                icon: 'https://blog.moeworld.tech/wp-content/themes/kratos-pjax-master/static/images/photo.jpg',
                archs: ['WordPress', 'Server'],
                date: '2024-02-25',
                comment: '技术折腾笔记。',
            },
            {
                name: 'Kegongteng',
                desc: 'Blogger / Technophile / Student',
                link: 'https://kegongteng.cn/',
                icon: 'https://bu.dusays.com/2023/12/23/65867c3357bb6.jpg',
                archs: ['Gridea', 'Vercel'],
                date: '2024-02-25',
                comment: '有不错想法的中学生。',
            },
            {
                name: '洛寒兮',
                desc: '这是个猫猫的博客喵～',
                link: 'https://www.luochancy.com/',
                icon: 'https://www.luochancy.com/wp-content/uploads/2023/12/1904634_Ehaif6np.png',
                archs: ['WordPress', 'Cloudflare'],
                date: '2024-03-01',
                comment: '高中生。',
            },
            {
                name: '清羽飞扬',
                desc: '柳影曳曳，清酒孤灯，扬笔撒墨，心境如霜',
                link: 'https://blog.liushen.fun/',
                icon: 'https://blog.liushen.fun/info/avatar.ico',
                archs: ['Hexo', 'CDN (国内)'],
                date: '2024-06-02',
                comment: '武理工学长，西安老乡。',
            },
            {
                name: 'awaae',
                title: '呓语梦轩',
                desc: '用心享受生活',
                link: 'https://blog.awaae001.top/',
                icon: 'https://image.m-c.top/?/images/2024/01/13/Pqeh0v6VaK/ico.jpg',
                archs: ['Hexo', 'CDN (国内)'],
                date: '2024-06-05',
                comment: '有思考的高中生。',
            },
            {
                name: '氿月',
                title: 'Lafcadia',
                desc: 'Et in Arcadia, ego.',
                link: 'https://chuishen.xyz/',
                icon: 'https://cravatar.cn/avatar/57ff1222a81493a0e72782530e77b269?s=160',
                archs: ['Hexo', 'Vercel'],
                date: '2024-06-16',
                comment: '文学；天体物理。',
            },
            {
                name: '晚夜',
                desc: '做好量变的准备，促进事物的质变。',
                link: 'https://www.iczrx.cn/',
                icon: 'https://q1.qlogo.cn/g?b=qq&nk=1463656527&s=4',
                archs: ['Typecho', 'Server'],
                date: '2024-07-11',
                comment: '分享折腾与生活的高中生。',
            },
            {
                name: '春日心动日记',
                desc: 'Live and learn. 🌱',
                link: 'https://blog.mletter.cn/',
                icon: 'https://img13.360buyimg.com/ddimg/jfs/t1/239095/17/9691/19853/664d82dfF34a0990c/c4198876146be2d4.jpg',
                archs: ['Hexo', 'Netlify'],
                date: '2024-07-11',
                comment: '在读运维开发工程师，记录技术和生活日常。',
            },
            {
                name: '天翔TNXG',
                title: '空间站',
                desc: '明日尚未到来，希望凝于心上',
                link: 'https://tnxgmoe.com/',
                icon: 'https://api-space.tnxg.top/avatar?s=qq',
                archs: ['Mix Space', 'Cloudflare'],
                date: '2024-07-11',
                comment: '西北地区高中生，开源爱好者。',
            },
            {
                name: 'Ariasaka',
                title: '小窝',
                desc: '人有悲欢离合 月有阴晴圆缺',
                link: 'https://blog.yaria.top/',
                icon: 'https://weavatar.com/avatar/795ce413eb6c7485954b78283ffa3e00?s=160',
                archs: ['Next.js', 'CDN (国内)'],
                date: '2024-07-12',
                comment: '初中生，OIer，折腾Hexo博客。',
            },
            {
                name: 'Winner365',
                title: '云栈',
                desc: '初阅不明言外意，重温方觉字中情',
                link: 'https://blog.365sites.top/',
                icon: 'https://blog.365sites.top/upload/avatar.png',
                archs: ['Halo', 'Cloudflare'],
                date: '2024-07-14',
                comment: '学生，折腾博客。',
            },
            {
                name: 'FloatSheep',
                desc: 'On the other side of obstacles',
                link: 'https://blog.hesiy.cn',
                icon: 'https://wsrv.nl/?url=github.com/FloatSheep.png',
                archs: ['Hugo', 'Deno Deploy'],
                date: '2024-07-24',
                comment: '喜欢折腾。',
            },
            {
                name: 'Henry Moreau',
                desc: 'Student / Designer / Dreamchaser',
                link: 'https://blog.henrywhu.cn/',
                icon: 'https://bu.dusays.com/2024/06/28/667e684e0adbe.png',
                archs: ['Gridea', 'Server'],
                date: '2024-07-24',
                comment: '高中生，很有博客的味道。',
            },
            {
                name: 'Xlenco',
                desc: '互联网中的静谧之地',
                link: 'https://blog.xlenco.top/',
                icon: 'https://q1.qlogo.cn/g?b=qq&nk=1043865083&s=4',
                archs: ['Nuxt', 'Vercel'],
                date: '2024-07-28',
                comment: '学生，经验分享。',
            },
            {
                name: '十玖八柒',
                title: 'Z次元',
                desc: '一个收藏回忆与分享技术的地方',
                link: 'https://blog.ahzoo.cn/',
                icon: 'https://blog.ahzoo.cn/avatar.webp',
                archs: ['Nuxt', 'Server'],
                date: '2024-08-02',
                comment: 'Nuxt博客，技术笔记。',
            },
            {
                name: 'iMaeGoo',
                title: '空间站',
                desc: '虹墨空间站',
                link: 'https://www.imaegoo.com/',
                icon: 'https://www.imaegoo.com/images/avatar.jpg',
                archs: ['Hexo', 'CDN (国内)'],
                date: '2024-08-19',
                comment: '前端折腾。',
            },
            {
                name: 'DuckXu',
                title: 'Hydda',
                desc: 'duckxu\'s internet home',
                link: 'https://i.duckxu.com/',
                icon: 'https://media.duckxu.com/blogfiles/public/iduckxucom.jpg',
                archs: ['Typecho', 'Server'],
                date: '2024-08-20',
                comment: '学生，记录生活思考。',
            },
            {
                name: '梦爱吃鱼',
                desc: '但愿日子清静抬头遇见的满是柔情',
                link: 'https://blog.bsgun.cn/',
                icon: 'https://oss-cdn.bsgun.cn/logo/avatar.256.png',
                archs: ['Hexo', 'CDN (国内)'],
                date: '2024-08-20',
                comment: '博客折腾。',
            },
            {
                name: '徐徐爱coding',
                desc: '一个精美的个人博客，记录平时的学习笔记',
                link: 'https://www.xu69.com',
                icon: 'https://www.xu69.com/xu-resource/ico.png',
                archs: ['Nuxt', 'CDN (国内)'],
                date: '2024-09-01',
                comment: '前端技术笔记，希望能做好响应式。',
            },
            {
                name: 'DengQN',
                desc: '普通程序员',
                link: 'https://dengqn.com/',
                icon: 'https://dengqn.com/image/headimg.png',
                archs: ['Vue', 'Server'],
                date: '2024-09-18',
                comment: '技术吐槽和运维记录。',
            },
            {
                name: 'LineXic',
                desc: '念念不忘，必有回响',
                link: 'https://blog.linexic.top/',
                icon: 'https://blog.linexic.top/logo.png',
                archs: ['Jekyll', 'Cloudflare'],
                date: '2024-10-02',
                comment: '前端学习，高中生活。',
            },
            {
                name: 'tinsir888',
                desc: 'Ηλύσια Πεδία',
                link: 'https://tinsir888.github.io/',
                icon: 'https://wsrv.nl/?url=github.com/tinsir888.png',
                archs: ['Hexo', 'GitHub Pages'],
                date: '2024-10-18',
                comment: '计算机科学，留学生活。',
            },
        ],
    },
    {
        name: '漫游',
        desc: '网上冲浪时发现的精彩内容，与君共享。',
        items: [
            {
                name: '风记星辰',
                link: 'https://thyuu.com/',
                icon: 'https://std.thyuu.com/logo.svg',
                archs: ['WordPress', 'Server'],
                date: '2024-02-01',
            },
            {
                name: '静かな森',
                link: 'https://innei.in/',
                icon: 'https://wsrv.nl/?url=github.com/Innei.png',
                archs: ['Mix Space', 'Cloudflare'],
                date: '2024-02-13',
            },
            {
                name: 'Randwind',
                link: 'https://www.randwind.com/',
                icon: 'https://wsrv.nl/?url=randwind.com/favicon.ico',
                archs: ['Hugo', 'Cloudflare'],
                date: '2024-02-03',
                comment: '一个喜欢折腾的 Web 前端开发者。2024-05-28 关闭友链功能。',
            },
            {
                name: 'Myth',
                link: 'https://myth.cx/',
                icon: 'https://myth.cx/img/avatar_hu4881e27882f65e048194c2e8319e9874_294915_300x0_resize_box_3.png',
                archs: ['Hugo', 'Cloudflare'],
                date: '2024-04-11',
            },
            {
                name: 'Dejavu',
                link: 'https://blog.dejavu.moe/',
                icon: 'https://blog.dejavu.moe/img/avatar_hu153f535f3685d84c2248f9e3bcb0c932_112544_288x288_fill_q75_h2_box_center_2.webp',
                archs: ['Hugo', 'Cloudflare'],
                date: '2024-04-29',
            },
            {
                name: '浪海导航',
                link: 'https://www.langhai.net/',
                icon: 'https://www.langhai.net/assets/images/langhai-logo.png',
                archs: ['Hugo', 'Cloudflare'],
                date: '2024-06-04',
            },
        ],
    },
]
